/* Generated by Yosys 0.58+84 (git sha1 f5c9e122d, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module Top_Module(clk, async_rst, Rx_Serial, Carry, Tx_Serial, \IO_OUT[0] , \IO_OUT[1] , \IO_OUT[2] , \IO_OUT[3] , \IO_OUT[4] , \IO_OUT[5] , \IO_OUT[6] , \IO_OUT[7] , \IO_OUT[8] , \IO_OUT[9] , \IO_OUT[10] , \IO_OUT[11] , \IO_OUT[12] , \IO_OUT[13] , \IO_OUT[14] , \IO_OUT[15] 
);
  input clk;
  wire clk;
  input async_rst;
  wire async_rst;
  input Rx_Serial;
  wire Rx_Serial;
  output Carry;
  wire Carry;
  output Tx_Serial;
  wire Tx_Serial;
  output \IO_OUT[0] ;
  wire \IO_OUT[0] ;
  output \IO_OUT[1] ;
  wire \IO_OUT[1] ;
  output \IO_OUT[2] ;
  wire \IO_OUT[2] ;
  output \IO_OUT[3] ;
  wire \IO_OUT[3] ;
  output \IO_OUT[4] ;
  wire \IO_OUT[4] ;
  output \IO_OUT[5] ;
  wire \IO_OUT[5] ;
  output \IO_OUT[6] ;
  wire \IO_OUT[6] ;
  output \IO_OUT[7] ;
  wire \IO_OUT[7] ;
  output \IO_OUT[8] ;
  wire \IO_OUT[8] ;
  output \IO_OUT[9] ;
  wire \IO_OUT[9] ;
  output \IO_OUT[10] ;
  wire \IO_OUT[10] ;
  output \IO_OUT[11] ;
  wire \IO_OUT[11] ;
  output \IO_OUT[12] ;
  wire \IO_OUT[12] ;
  output \IO_OUT[13] ;
  wire \IO_OUT[13] ;
  output \IO_OUT[14] ;
  wire \IO_OUT[14] ;
  output \IO_OUT[15] ;
  wire \IO_OUT[15] ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire \ALUControlHZ[0] ;
  wire \ALUControlHZ[1] ;
  wire \ALUControlHZ[2] ;
  wire \ALUControlHZ[3] ;
  wire \ALUControlHZ[4] ;
  wire \ALUControl[0] ;
  wire \ALUControl[1] ;
  wire \ALUControl[2] ;
  wire \ALUControl[3] ;
  wire \ALUControl[4] ;
  wire \ALUControl_ID[0] ;
  wire \ALUControl_ID[1] ;
  wire \ALUControl_ID[2] ;
  wire \ALUControl_ID[3] ;
  wire \ALUControl_ID[4] ;
  wire ALUSrc;
  wire ALUSrcHZ;
  wire ALUSrc_ID;
  wire \ALUresult[0] ;
  wire \ALUresult[10] ;
  wire \ALUresult[11] ;
  wire \ALUresult[12] ;
  wire \ALUresult[13] ;
  wire \ALUresult[14] ;
  wire \ALUresult[15] ;
  wire \ALUresult[16] ;
  wire \ALUresult[17] ;
  wire \ALUresult[18] ;
  wire \ALUresult[19] ;
  wire \ALUresult[1] ;
  wire \ALUresult[20] ;
  wire \ALUresult[21] ;
  wire \ALUresult[22] ;
  wire \ALUresult[23] ;
  wire \ALUresult[24] ;
  wire \ALUresult[25] ;
  wire \ALUresult[26] ;
  wire \ALUresult[27] ;
  wire \ALUresult[28] ;
  wire \ALUresult[29] ;
  wire \ALUresult[2] ;
  wire \ALUresult[30] ;
  wire \ALUresult[31] ;
  wire \ALUresult[3] ;
  wire \ALUresult[4] ;
  wire \ALUresult[5] ;
  wire \ALUresult[6] ;
  wire \ALUresult[7] ;
  wire \ALUresult[8] ;
  wire \ALUresult[9] ;
  wire \ALUresult_EX[0] ;
  wire \ALUresult_EX[10] ;
  wire \ALUresult_EX[11] ;
  wire \ALUresult_EX[12] ;
  wire \ALUresult_EX[13] ;
  wire \ALUresult_EX[14] ;
  wire \ALUresult_EX[15] ;
  wire \ALUresult_EX[16] ;
  wire \ALUresult_EX[17] ;
  wire \ALUresult_EX[18] ;
  wire \ALUresult_EX[19] ;
  wire \ALUresult_EX[1] ;
  wire \ALUresult_EX[20] ;
  wire \ALUresult_EX[21] ;
  wire \ALUresult_EX[22] ;
  wire \ALUresult_EX[23] ;
  wire \ALUresult_EX[24] ;
  wire \ALUresult_EX[25] ;
  wire \ALUresult_EX[26] ;
  wire \ALUresult_EX[27] ;
  wire \ALUresult_EX[28] ;
  wire \ALUresult_EX[29] ;
  wire \ALUresult_EX[2] ;
  wire \ALUresult_EX[30] ;
  wire \ALUresult_EX[31] ;
  wire \ALUresult_EX[3] ;
  wire \ALUresult_EX[4] ;
  wire \ALUresult_EX[5] ;
  wire \ALUresult_EX[6] ;
  wire \ALUresult_EX[7] ;
  wire \ALUresult_EX[8] ;
  wire \ALUresult_EX[9] ;
  wire \ALUresult_MEM[0] ;
  wire \ALUresult_MEM[10] ;
  wire \ALUresult_MEM[11] ;
  wire \ALUresult_MEM[12] ;
  wire \ALUresult_MEM[13] ;
  wire \ALUresult_MEM[14] ;
  wire \ALUresult_MEM[15] ;
  wire \ALUresult_MEM[16] ;
  wire \ALUresult_MEM[17] ;
  wire \ALUresult_MEM[18] ;
  wire \ALUresult_MEM[19] ;
  wire \ALUresult_MEM[1] ;
  wire \ALUresult_MEM[20] ;
  wire \ALUresult_MEM[21] ;
  wire \ALUresult_MEM[22] ;
  wire \ALUresult_MEM[23] ;
  wire \ALUresult_MEM[24] ;
  wire \ALUresult_MEM[25] ;
  wire \ALUresult_MEM[26] ;
  wire \ALUresult_MEM[27] ;
  wire \ALUresult_MEM[28] ;
  wire \ALUresult_MEM[29] ;
  wire \ALUresult_MEM[2] ;
  wire \ALUresult_MEM[30] ;
  wire \ALUresult_MEM[31] ;
  wire \ALUresult_MEM[3] ;
  wire \ALUresult_MEM[4] ;
  wire \ALUresult_MEM[5] ;
  wire \ALUresult_MEM[6] ;
  wire \ALUresult_MEM[7] ;
  wire \ALUresult_MEM[8] ;
  wire \ALUresult_MEM[9] ;
  wire B_Zero;
  wire B_Zero_ID;
  wire Branch;
  wire BranchHZ;
  wire Branch_ID;
  wire \FIFO_Rx_Dout[0] ;
  wire \FIFO_Rx_Dout[1] ;
  wire \FIFO_Rx_Dout[2] ;
  wire \FIFO_Rx_Dout[3] ;
  wire \FIFO_Rx_Dout[4] ;
  wire \FIFO_Rx_Dout[5] ;
  wire \FIFO_Rx_Dout[6] ;
  wire \FIFO_Rx_Dout[7] ;
  wire Flush;
  wire \ForwardA[0] ;
  wire \ForwardA[1] ;
  wire \ForwardB[0] ;
  wire \ForwardB[1] ;
  wire IF_ID_WriteEN;
  wire \ImmExt[0] ;
  wire \ImmExt[10] ;
  wire \ImmExt[11] ;
  wire \ImmExt[12] ;
  wire \ImmExt[13] ;
  wire \ImmExt[14] ;
  wire \ImmExt[15] ;
  wire \ImmExt[16] ;
  wire \ImmExt[17] ;
  wire \ImmExt[18] ;
  wire \ImmExt[19] ;
  wire \ImmExt[1] ;
  wire \ImmExt[20] ;
  wire \ImmExt[21] ;
  wire \ImmExt[22] ;
  wire \ImmExt[23] ;
  wire \ImmExt[24] ;
  wire \ImmExt[25] ;
  wire \ImmExt[26] ;
  wire \ImmExt[27] ;
  wire \ImmExt[28] ;
  wire \ImmExt[29] ;
  wire \ImmExt[2] ;
  wire \ImmExt[30] ;
  wire \ImmExt[31] ;
  wire \ImmExt[3] ;
  wire \ImmExt[4] ;
  wire \ImmExt[5] ;
  wire \ImmExt[6] ;
  wire \ImmExt[7] ;
  wire \ImmExt[8] ;
  wire \ImmExt[9] ;
  wire \ImmExt_ID[0] ;
  wire \ImmExt_ID[10] ;
  wire \ImmExt_ID[11] ;
  wire \ImmExt_ID[12] ;
  wire \ImmExt_ID[13] ;
  wire \ImmExt_ID[14] ;
  wire \ImmExt_ID[15] ;
  wire \ImmExt_ID[16] ;
  wire \ImmExt_ID[17] ;
  wire \ImmExt_ID[18] ;
  wire \ImmExt_ID[19] ;
  wire \ImmExt_ID[1] ;
  wire \ImmExt_ID[20] ;
  wire \ImmExt_ID[21] ;
  wire \ImmExt_ID[22] ;
  wire \ImmExt_ID[23] ;
  wire \ImmExt_ID[24] ;
  wire \ImmExt_ID[25] ;
  wire \ImmExt_ID[26] ;
  wire \ImmExt_ID[27] ;
  wire \ImmExt_ID[28] ;
  wire \ImmExt_ID[29] ;
  wire \ImmExt_ID[2] ;
  wire \ImmExt_ID[30] ;
  wire \ImmExt_ID[31] ;
  wire \ImmExt_ID[3] ;
  wire \ImmExt_ID[4] ;
  wire \ImmExt_ID[5] ;
  wire \ImmExt_ID[6] ;
  wire \ImmExt_ID[7] ;
  wire \ImmExt_ID[8] ;
  wire \ImmExt_ID[9] ;
  wire \ImmType[0] ;
  wire \ImmType[1] ;
  wire \ImmType[2] ;
  wire Jump;
  wire JumpHZ;
  wire JumpReg;
  wire JumpRegHZ;
  wire JumpReg_ID;
  wire Jump_ID;
  wire MemRead;
  wire \MemReadData[0] ;
  wire \MemReadData[10] ;
  wire \MemReadData[11] ;
  wire \MemReadData[12] ;
  wire \MemReadData[13] ;
  wire \MemReadData[14] ;
  wire \MemReadData[15] ;
  wire \MemReadData[16] ;
  wire \MemReadData[17] ;
  wire \MemReadData[18] ;
  wire \MemReadData[19] ;
  wire \MemReadData[1] ;
  wire \MemReadData[20] ;
  wire \MemReadData[21] ;
  wire \MemReadData[22] ;
  wire \MemReadData[23] ;
  wire \MemReadData[24] ;
  wire \MemReadData[25] ;
  wire \MemReadData[26] ;
  wire \MemReadData[27] ;
  wire \MemReadData[28] ;
  wire \MemReadData[29] ;
  wire \MemReadData[2] ;
  wire \MemReadData[30] ;
  wire \MemReadData[31] ;
  wire \MemReadData[3] ;
  wire \MemReadData[4] ;
  wire \MemReadData[5] ;
  wire \MemReadData[6] ;
  wire \MemReadData[7] ;
  wire \MemReadData[8] ;
  wire \MemReadData[9] ;
  wire \MemReadData_MEM[0] ;
  wire \MemReadData_MEM[10] ;
  wire \MemReadData_MEM[11] ;
  wire \MemReadData_MEM[12] ;
  wire \MemReadData_MEM[13] ;
  wire \MemReadData_MEM[14] ;
  wire \MemReadData_MEM[15] ;
  wire \MemReadData_MEM[16] ;
  wire \MemReadData_MEM[17] ;
  wire \MemReadData_MEM[18] ;
  wire \MemReadData_MEM[19] ;
  wire \MemReadData_MEM[1] ;
  wire \MemReadData_MEM[20] ;
  wire \MemReadData_MEM[21] ;
  wire \MemReadData_MEM[22] ;
  wire \MemReadData_MEM[23] ;
  wire \MemReadData_MEM[24] ;
  wire \MemReadData_MEM[25] ;
  wire \MemReadData_MEM[26] ;
  wire \MemReadData_MEM[27] ;
  wire \MemReadData_MEM[28] ;
  wire \MemReadData_MEM[29] ;
  wire \MemReadData_MEM[2] ;
  wire \MemReadData_MEM[30] ;
  wire \MemReadData_MEM[31] ;
  wire \MemReadData_MEM[3] ;
  wire \MemReadData_MEM[4] ;
  wire \MemReadData_MEM[5] ;
  wire \MemReadData_MEM[6] ;
  wire \MemReadData_MEM[7] ;
  wire \MemReadData_MEM[8] ;
  wire \MemReadData_MEM[9] ;
  wire MemReadHZ;
  wire MemWrite;
  wire MemWriteHZ;
  wire \Mem_Con_EX[0] ;
  wire \Mem_Con_EX[1] ;
  wire \Mem_Con_ID[0] ;
  wire \Mem_Con_ID[1] ;
  wire NOP;
  wire \PCPlus4[0] ;
  wire \PCPlus4[10] ;
  wire \PCPlus4[11] ;
  wire \PCPlus4[12] ;
  wire \PCPlus4[13] ;
  wire \PCPlus4[14] ;
  wire \PCPlus4[15] ;
  wire \PCPlus4[16] ;
  wire \PCPlus4[17] ;
  wire \PCPlus4[18] ;
  wire \PCPlus4[19] ;
  wire \PCPlus4[1] ;
  wire \PCPlus4[20] ;
  wire \PCPlus4[21] ;
  wire \PCPlus4[22] ;
  wire \PCPlus4[23] ;
  wire \PCPlus4[24] ;
  wire \PCPlus4[25] ;
  wire \PCPlus4[26] ;
  wire \PCPlus4[27] ;
  wire \PCPlus4[28] ;
  wire \PCPlus4[29] ;
  wire \PCPlus4[2] ;
  wire \PCPlus4[30] ;
  wire \PCPlus4[31] ;
  wire \PCPlus4[3] ;
  wire \PCPlus4[4] ;
  wire \PCPlus4[5] ;
  wire \PCPlus4[6] ;
  wire \PCPlus4[7] ;
  wire \PCPlus4[8] ;
  wire \PCPlus4[9] ;
  wire PCSrc;
  wire PCWriteEN;
  wire \PC[0] ;
  wire \PC[10] ;
  wire \PC[11] ;
  wire \PC[12] ;
  wire \PC[13] ;
  wire \PC[14] ;
  wire \PC[15] ;
  wire \PC[16] ;
  wire \PC[17] ;
  wire \PC[18] ;
  wire \PC[19] ;
  wire \PC[1] ;
  wire \PC[20] ;
  wire \PC[21] ;
  wire \PC[22] ;
  wire \PC[23] ;
  wire \PC[24] ;
  wire \PC[25] ;
  wire \PC[26] ;
  wire \PC[27] ;
  wire \PC[28] ;
  wire \PC[29] ;
  wire \PC[2] ;
  wire \PC[30] ;
  wire \PC[31] ;
  wire \PC[3] ;
  wire \PC[4] ;
  wire \PC[5] ;
  wire \PC[6] ;
  wire \PC[7] ;
  wire \PC[8] ;
  wire \PC[9] ;
  wire \PC_ALU_Sum[0] ;
  wire \PC_ALU_Sum[10] ;
  wire \PC_ALU_Sum[11] ;
  wire \PC_ALU_Sum[12] ;
  wire \PC_ALU_Sum[13] ;
  wire \PC_ALU_Sum[14] ;
  wire \PC_ALU_Sum[15] ;
  wire \PC_ALU_Sum[16] ;
  wire \PC_ALU_Sum[17] ;
  wire \PC_ALU_Sum[18] ;
  wire \PC_ALU_Sum[19] ;
  wire \PC_ALU_Sum[1] ;
  wire \PC_ALU_Sum[20] ;
  wire \PC_ALU_Sum[21] ;
  wire \PC_ALU_Sum[22] ;
  wire \PC_ALU_Sum[23] ;
  wire \PC_ALU_Sum[24] ;
  wire \PC_ALU_Sum[25] ;
  wire \PC_ALU_Sum[26] ;
  wire \PC_ALU_Sum[27] ;
  wire \PC_ALU_Sum[28] ;
  wire \PC_ALU_Sum[29] ;
  wire \PC_ALU_Sum[2] ;
  wire \PC_ALU_Sum[30] ;
  wire \PC_ALU_Sum[31] ;
  wire \PC_ALU_Sum[3] ;
  wire \PC_ALU_Sum[4] ;
  wire \PC_ALU_Sum[5] ;
  wire \PC_ALU_Sum[6] ;
  wire \PC_ALU_Sum[7] ;
  wire \PC_ALU_Sum[8] ;
  wire \PC_ALU_Sum[9] ;
  wire \PC_Branch[0] ;
  wire \PC_Branch[10] ;
  wire \PC_Branch[11] ;
  wire \PC_Branch[12] ;
  wire \PC_Branch[13] ;
  wire \PC_Branch[14] ;
  wire \PC_Branch[15] ;
  wire \PC_Branch[16] ;
  wire \PC_Branch[17] ;
  wire \PC_Branch[18] ;
  wire \PC_Branch[19] ;
  wire \PC_Branch[1] ;
  wire \PC_Branch[20] ;
  wire \PC_Branch[21] ;
  wire \PC_Branch[22] ;
  wire \PC_Branch[23] ;
  wire \PC_Branch[24] ;
  wire \PC_Branch[25] ;
  wire \PC_Branch[26] ;
  wire \PC_Branch[27] ;
  wire \PC_Branch[28] ;
  wire \PC_Branch[29] ;
  wire \PC_Branch[2] ;
  wire \PC_Branch[30] ;
  wire \PC_Branch[31] ;
  wire \PC_Branch[3] ;
  wire \PC_Branch[4] ;
  wire \PC_Branch[5] ;
  wire \PC_Branch[6] ;
  wire \PC_Branch[7] ;
  wire \PC_Branch[8] ;
  wire \PC_Branch[9] ;
  wire \PC_ID[0] ;
  wire \PC_ID[10] ;
  wire \PC_ID[11] ;
  wire \PC_ID[12] ;
  wire \PC_ID[13] ;
  wire \PC_ID[14] ;
  wire \PC_ID[15] ;
  wire \PC_ID[16] ;
  wire \PC_ID[17] ;
  wire \PC_ID[18] ;
  wire \PC_ID[19] ;
  wire \PC_ID[1] ;
  wire \PC_ID[20] ;
  wire \PC_ID[21] ;
  wire \PC_ID[22] ;
  wire \PC_ID[23] ;
  wire \PC_ID[24] ;
  wire \PC_ID[25] ;
  wire \PC_ID[26] ;
  wire \PC_ID[27] ;
  wire \PC_ID[28] ;
  wire \PC_ID[29] ;
  wire \PC_ID[2] ;
  wire \PC_ID[30] ;
  wire \PC_ID[31] ;
  wire \PC_ID[3] ;
  wire \PC_ID[4] ;
  wire \PC_ID[5] ;
  wire \PC_ID[6] ;
  wire \PC_ID[7] ;
  wire \PC_ID[8] ;
  wire \PC_ID[9] ;
  wire \PC_IF[0] ;
  wire \PC_IF[10] ;
  wire \PC_IF[11] ;
  wire \PC_IF[12] ;
  wire \PC_IF[13] ;
  wire \PC_IF[14] ;
  wire \PC_IF[15] ;
  wire \PC_IF[16] ;
  wire \PC_IF[17] ;
  wire \PC_IF[18] ;
  wire \PC_IF[19] ;
  wire \PC_IF[1] ;
  wire \PC_IF[20] ;
  wire \PC_IF[21] ;
  wire \PC_IF[22] ;
  wire \PC_IF[23] ;
  wire \PC_IF[24] ;
  wire \PC_IF[25] ;
  wire \PC_IF[26] ;
  wire \PC_IF[27] ;
  wire \PC_IF[28] ;
  wire \PC_IF[29] ;
  wire \PC_IF[2] ;
  wire \PC_IF[30] ;
  wire \PC_IF[31] ;
  wire \PC_IF[3] ;
  wire \PC_IF[4] ;
  wire \PC_IF[5] ;
  wire \PC_IF[6] ;
  wire \PC_IF[7] ;
  wire \PC_IF[8] ;
  wire \PC_IF[9] ;
  wire \PC_next[0] ;
  wire \PC_next[10] ;
  wire \PC_next[11] ;
  wire \PC_next[12] ;
  wire \PC_next[13] ;
  wire \PC_next[14] ;
  wire \PC_next[15] ;
  wire \PC_next[16] ;
  wire \PC_next[17] ;
  wire \PC_next[18] ;
  wire \PC_next[19] ;
  wire \PC_next[1] ;
  wire \PC_next[20] ;
  wire \PC_next[21] ;
  wire \PC_next[22] ;
  wire \PC_next[23] ;
  wire \PC_next[24] ;
  wire \PC_next[25] ;
  wire \PC_next[26] ;
  wire \PC_next[27] ;
  wire \PC_next[28] ;
  wire \PC_next[29] ;
  wire \PC_next[2] ;
  wire \PC_next[30] ;
  wire \PC_next[31] ;
  wire \PC_next[3] ;
  wire \PC_next[4] ;
  wire \PC_next[5] ;
  wire \PC_next[6] ;
  wire \PC_next[7] ;
  wire \PC_next[8] ;
  wire \PC_next[9] ;
  wire \PC_next_EX[0] ;
  wire \PC_next_EX[10] ;
  wire \PC_next_EX[11] ;
  wire \PC_next_EX[12] ;
  wire \PC_next_EX[13] ;
  wire \PC_next_EX[14] ;
  wire \PC_next_EX[15] ;
  wire \PC_next_EX[16] ;
  wire \PC_next_EX[17] ;
  wire \PC_next_EX[18] ;
  wire \PC_next_EX[19] ;
  wire \PC_next_EX[1] ;
  wire \PC_next_EX[20] ;
  wire \PC_next_EX[21] ;
  wire \PC_next_EX[22] ;
  wire \PC_next_EX[23] ;
  wire \PC_next_EX[24] ;
  wire \PC_next_EX[25] ;
  wire \PC_next_EX[26] ;
  wire \PC_next_EX[27] ;
  wire \PC_next_EX[28] ;
  wire \PC_next_EX[29] ;
  wire \PC_next_EX[2] ;
  wire \PC_next_EX[30] ;
  wire \PC_next_EX[31] ;
  wire \PC_next_EX[3] ;
  wire \PC_next_EX[4] ;
  wire \PC_next_EX[5] ;
  wire \PC_next_EX[6] ;
  wire \PC_next_EX[7] ;
  wire \PC_next_EX[8] ;
  wire \PC_next_EX[9] ;
  wire \PC_next_ID[0] ;
  wire \PC_next_ID[10] ;
  wire \PC_next_ID[11] ;
  wire \PC_next_ID[12] ;
  wire \PC_next_ID[13] ;
  wire \PC_next_ID[14] ;
  wire \PC_next_ID[15] ;
  wire \PC_next_ID[16] ;
  wire \PC_next_ID[17] ;
  wire \PC_next_ID[18] ;
  wire \PC_next_ID[19] ;
  wire \PC_next_ID[1] ;
  wire \PC_next_ID[20] ;
  wire \PC_next_ID[21] ;
  wire \PC_next_ID[22] ;
  wire \PC_next_ID[23] ;
  wire \PC_next_ID[24] ;
  wire \PC_next_ID[25] ;
  wire \PC_next_ID[26] ;
  wire \PC_next_ID[27] ;
  wire \PC_next_ID[28] ;
  wire \PC_next_ID[29] ;
  wire \PC_next_ID[2] ;
  wire \PC_next_ID[30] ;
  wire \PC_next_ID[31] ;
  wire \PC_next_ID[3] ;
  wire \PC_next_ID[4] ;
  wire \PC_next_ID[5] ;
  wire \PC_next_ID[6] ;
  wire \PC_next_ID[7] ;
  wire \PC_next_ID[8] ;
  wire \PC_next_ID[9] ;
  wire \PC_next_IF[0] ;
  wire \PC_next_IF[10] ;
  wire \PC_next_IF[11] ;
  wire \PC_next_IF[12] ;
  wire \PC_next_IF[13] ;
  wire \PC_next_IF[14] ;
  wire \PC_next_IF[15] ;
  wire \PC_next_IF[16] ;
  wire \PC_next_IF[17] ;
  wire \PC_next_IF[18] ;
  wire \PC_next_IF[19] ;
  wire \PC_next_IF[1] ;
  wire \PC_next_IF[20] ;
  wire \PC_next_IF[21] ;
  wire \PC_next_IF[22] ;
  wire \PC_next_IF[23] ;
  wire \PC_next_IF[24] ;
  wire \PC_next_IF[25] ;
  wire \PC_next_IF[26] ;
  wire \PC_next_IF[27] ;
  wire \PC_next_IF[28] ;
  wire \PC_next_IF[29] ;
  wire \PC_next_IF[2] ;
  wire \PC_next_IF[30] ;
  wire \PC_next_IF[31] ;
  wire \PC_next_IF[3] ;
  wire \PC_next_IF[4] ;
  wire \PC_next_IF[5] ;
  wire \PC_next_IF[6] ;
  wire \PC_next_IF[7] ;
  wire \PC_next_IF[8] ;
  wire \PC_next_IF[9] ;
  wire \PC_next_MEM[0] ;
  wire \PC_next_MEM[10] ;
  wire \PC_next_MEM[11] ;
  wire \PC_next_MEM[12] ;
  wire \PC_next_MEM[13] ;
  wire \PC_next_MEM[14] ;
  wire \PC_next_MEM[15] ;
  wire \PC_next_MEM[16] ;
  wire \PC_next_MEM[17] ;
  wire \PC_next_MEM[18] ;
  wire \PC_next_MEM[19] ;
  wire \PC_next_MEM[1] ;
  wire \PC_next_MEM[20] ;
  wire \PC_next_MEM[21] ;
  wire \PC_next_MEM[22] ;
  wire \PC_next_MEM[23] ;
  wire \PC_next_MEM[24] ;
  wire \PC_next_MEM[25] ;
  wire \PC_next_MEM[26] ;
  wire \PC_next_MEM[27] ;
  wire \PC_next_MEM[28] ;
  wire \PC_next_MEM[29] ;
  wire \PC_next_MEM[2] ;
  wire \PC_next_MEM[30] ;
  wire \PC_next_MEM[31] ;
  wire \PC_next_MEM[3] ;
  wire \PC_next_MEM[4] ;
  wire \PC_next_MEM[5] ;
  wire \PC_next_MEM[6] ;
  wire \PC_next_MEM[7] ;
  wire \PC_next_MEM[8] ;
  wire \PC_next_MEM[9] ;
  wire RegWrite;
  wire RegWriteHZ;
  wire RegWrite_EX;
  wire RegWrite_ID;
  wire RegWrite_MEM;
  wire \ResultSrcHZ[0] ;
  wire \ResultSrcHZ[1] ;
  wire \ResultSrc[0] ;
  wire \ResultSrc[1] ;
  wire \ResultSrc_EX[0] ;
  wire \ResultSrc_EX[1] ;
  wire \ResultSrc_ID[0] ;
  wire \ResultSrc_ID[1] ;
  wire \ResultSrc_MEM[0] ;
  wire \ResultSrc_MEM[1] ;
  wire \Result[0] ;
  wire \Result[10] ;
  wire \Result[11] ;
  wire \Result[12] ;
  wire \Result[13] ;
  wire \Result[14] ;
  wire \Result[15] ;
  wire \Result[16] ;
  wire \Result[17] ;
  wire \Result[18] ;
  wire \Result[19] ;
  wire \Result[1] ;
  wire \Result[20] ;
  wire \Result[21] ;
  wire \Result[22] ;
  wire \Result[23] ;
  wire \Result[24] ;
  wire \Result[25] ;
  wire \Result[26] ;
  wire \Result[27] ;
  wire \Result[28] ;
  wire \Result[29] ;
  wire \Result[2] ;
  wire \Result[30] ;
  wire \Result[31] ;
  wire \Result[3] ;
  wire \Result[4] ;
  wire \Result[5] ;
  wire \Result[6] ;
  wire \Result[7] ;
  wire \Result[8] ;
  wire \Result[9] ;
  wire Rx_read_en;
  wire \UART_Mem_wt[0] ;
  wire \UART_Mem_wt[1] ;
  wire Zero;
  wire \compress_instr[0] ;
  wire \compress_instr[10] ;
  wire \compress_instr[11] ;
  wire \compress_instr[12] ;
  wire \compress_instr[13] ;
  wire \compress_instr[14] ;
  wire \compress_instr[15] ;
  wire \compress_instr[16] ;
  wire \compress_instr[17] ;
  wire \compress_instr[18] ;
  wire \compress_instr[19] ;
  wire \compress_instr[1] ;
  wire \compress_instr[20] ;
  wire \compress_instr[21] ;
  wire \compress_instr[22] ;
  wire \compress_instr[23] ;
  wire \compress_instr[24] ;
  wire \compress_instr[25] ;
  wire \compress_instr[26] ;
  wire \compress_instr[27] ;
  wire \compress_instr[28] ;
  wire \compress_instr[29] ;
  wire \compress_instr[2] ;
  wire \compress_instr[30] ;
  wire \compress_instr[31] ;
  wire \compress_instr[3] ;
  wire \compress_instr[4] ;
  wire \compress_instr[5] ;
  wire \compress_instr[6] ;
  wire \compress_instr[7] ;
  wire \compress_instr[8] ;
  wire \compress_instr[9] ;
  wire \data1[0] ;
  wire \data1[10] ;
  wire \data1[11] ;
  wire \data1[12] ;
  wire \data1[13] ;
  wire \data1[14] ;
  wire \data1[15] ;
  wire \data1[16] ;
  wire \data1[17] ;
  wire \data1[18] ;
  wire \data1[19] ;
  wire \data1[1] ;
  wire \data1[20] ;
  wire \data1[21] ;
  wire \data1[22] ;
  wire \data1[23] ;
  wire \data1[24] ;
  wire \data1[25] ;
  wire \data1[26] ;
  wire \data1[27] ;
  wire \data1[28] ;
  wire \data1[29] ;
  wire \data1[2] ;
  wire \data1[30] ;
  wire \data1[31] ;
  wire \data1[3] ;
  wire \data1[4] ;
  wire \data1[5] ;
  wire \data1[6] ;
  wire \data1[7] ;
  wire \data1[8] ;
  wire \data1[9] ;
  wire \data1_ID[0] ;
  wire \data1_ID[10] ;
  wire \data1_ID[11] ;
  wire \data1_ID[12] ;
  wire \data1_ID[13] ;
  wire \data1_ID[14] ;
  wire \data1_ID[15] ;
  wire \data1_ID[16] ;
  wire \data1_ID[17] ;
  wire \data1_ID[18] ;
  wire \data1_ID[19] ;
  wire \data1_ID[1] ;
  wire \data1_ID[20] ;
  wire \data1_ID[21] ;
  wire \data1_ID[22] ;
  wire \data1_ID[23] ;
  wire \data1_ID[24] ;
  wire \data1_ID[25] ;
  wire \data1_ID[26] ;
  wire \data1_ID[27] ;
  wire \data1_ID[28] ;
  wire \data1_ID[29] ;
  wire \data1_ID[2] ;
  wire \data1_ID[30] ;
  wire \data1_ID[31] ;
  wire \data1_ID[3] ;
  wire \data1_ID[4] ;
  wire \data1_ID[5] ;
  wire \data1_ID[6] ;
  wire \data1_ID[7] ;
  wire \data1_ID[8] ;
  wire \data1_ID[9] ;
  wire \data1_ID_ForwA[0] ;
  wire \data1_ID_ForwA[10] ;
  wire \data1_ID_ForwA[11] ;
  wire \data1_ID_ForwA[12] ;
  wire \data1_ID_ForwA[13] ;
  wire \data1_ID_ForwA[14] ;
  wire \data1_ID_ForwA[15] ;
  wire \data1_ID_ForwA[16] ;
  wire \data1_ID_ForwA[17] ;
  wire \data1_ID_ForwA[18] ;
  wire \data1_ID_ForwA[19] ;
  wire \data1_ID_ForwA[1] ;
  wire \data1_ID_ForwA[20] ;
  wire \data1_ID_ForwA[21] ;
  wire \data1_ID_ForwA[22] ;
  wire \data1_ID_ForwA[23] ;
  wire \data1_ID_ForwA[24] ;
  wire \data1_ID_ForwA[25] ;
  wire \data1_ID_ForwA[26] ;
  wire \data1_ID_ForwA[27] ;
  wire \data1_ID_ForwA[28] ;
  wire \data1_ID_ForwA[29] ;
  wire \data1_ID_ForwA[2] ;
  wire \data1_ID_ForwA[30] ;
  wire \data1_ID_ForwA[31] ;
  wire \data1_ID_ForwA[3] ;
  wire \data1_ID_ForwA[4] ;
  wire \data1_ID_ForwA[5] ;
  wire \data1_ID_ForwA[6] ;
  wire \data1_ID_ForwA[7] ;
  wire \data1_ID_ForwA[8] ;
  wire \data1_ID_ForwA[9] ;
  wire \data2[0] ;
  wire \data2[10] ;
  wire \data2[11] ;
  wire \data2[12] ;
  wire \data2[13] ;
  wire \data2[14] ;
  wire \data2[15] ;
  wire \data2[16] ;
  wire \data2[17] ;
  wire \data2[18] ;
  wire \data2[19] ;
  wire \data2[1] ;
  wire \data2[20] ;
  wire \data2[21] ;
  wire \data2[22] ;
  wire \data2[23] ;
  wire \data2[24] ;
  wire \data2[25] ;
  wire \data2[26] ;
  wire \data2[27] ;
  wire \data2[28] ;
  wire \data2[29] ;
  wire \data2[2] ;
  wire \data2[30] ;
  wire \data2[31] ;
  wire \data2[3] ;
  wire \data2[4] ;
  wire \data2[5] ;
  wire \data2[6] ;
  wire \data2[7] ;
  wire \data2[8] ;
  wire \data2[9] ;
  wire \data2_EX[0] ;
  wire \data2_EX[10] ;
  wire \data2_EX[11] ;
  wire \data2_EX[12] ;
  wire \data2_EX[13] ;
  wire \data2_EX[14] ;
  wire \data2_EX[15] ;
  wire \data2_EX[16] ;
  wire \data2_EX[17] ;
  wire \data2_EX[18] ;
  wire \data2_EX[19] ;
  wire \data2_EX[1] ;
  wire \data2_EX[20] ;
  wire \data2_EX[21] ;
  wire \data2_EX[22] ;
  wire \data2_EX[23] ;
  wire \data2_EX[24] ;
  wire \data2_EX[25] ;
  wire \data2_EX[26] ;
  wire \data2_EX[27] ;
  wire \data2_EX[28] ;
  wire \data2_EX[29] ;
  wire \data2_EX[2] ;
  wire \data2_EX[30] ;
  wire \data2_EX[31] ;
  wire \data2_EX[3] ;
  wire \data2_EX[4] ;
  wire \data2_EX[5] ;
  wire \data2_EX[6] ;
  wire \data2_EX[7] ;
  wire \data2_EX[8] ;
  wire \data2_EX[9] ;
  wire \data2_ID[0] ;
  wire \data2_ID[10] ;
  wire \data2_ID[11] ;
  wire \data2_ID[12] ;
  wire \data2_ID[13] ;
  wire \data2_ID[14] ;
  wire \data2_ID[15] ;
  wire \data2_ID[16] ;
  wire \data2_ID[17] ;
  wire \data2_ID[18] ;
  wire \data2_ID[19] ;
  wire \data2_ID[1] ;
  wire \data2_ID[20] ;
  wire \data2_ID[21] ;
  wire \data2_ID[22] ;
  wire \data2_ID[23] ;
  wire \data2_ID[24] ;
  wire \data2_ID[25] ;
  wire \data2_ID[26] ;
  wire \data2_ID[27] ;
  wire \data2_ID[28] ;
  wire \data2_ID[29] ;
  wire \data2_ID[2] ;
  wire \data2_ID[30] ;
  wire \data2_ID[31] ;
  wire \data2_ID[3] ;
  wire \data2_ID[4] ;
  wire \data2_ID[5] ;
  wire \data2_ID[6] ;
  wire \data2_ID[7] ;
  wire \data2_ID[8] ;
  wire \data2_ID[9] ;
  wire div_active;
  wire empty_Rx;
  wire full_Rx;
  wire \initial_instr[0] ;
  wire \initial_instr[10] ;
  wire \initial_instr[11] ;
  wire \initial_instr[12] ;
  wire \initial_instr[13] ;
  wire \initial_instr[14] ;
  wire \initial_instr[15] ;
  wire \initial_instr[16] ;
  wire \initial_instr[17] ;
  wire \initial_instr[18] ;
  wire \initial_instr[19] ;
  wire \initial_instr[1] ;
  wire \initial_instr[20] ;
  wire \initial_instr[21] ;
  wire \initial_instr[22] ;
  wire \initial_instr[23] ;
  wire \initial_instr[24] ;
  wire \initial_instr[25] ;
  wire \initial_instr[26] ;
  wire \initial_instr[27] ;
  wire \initial_instr[28] ;
  wire \initial_instr[29] ;
  wire \initial_instr[2] ;
  wire \initial_instr[30] ;
  wire \initial_instr[31] ;
  wire \initial_instr[3] ;
  wire \initial_instr[4] ;
  wire \initial_instr[5] ;
  wire \initial_instr[6] ;
  wire \initial_instr[7] ;
  wire \initial_instr[8] ;
  wire \initial_instr[9] ;
  wire \instruction[0] ;
  wire \instruction[10] ;
  wire \instruction[11] ;
  wire \instruction[12] ;
  wire \instruction[13] ;
  wire \instruction[14] ;
  wire \instruction[15] ;
  wire \instruction[16] ;
  wire \instruction[17] ;
  wire \instruction[18] ;
  wire \instruction[19] ;
  wire \instruction[1] ;
  wire \instruction[20] ;
  wire \instruction[21] ;
  wire \instruction[22] ;
  wire \instruction[23] ;
  wire \instruction[24] ;
  wire \instruction[25] ;
  wire \instruction[26] ;
  wire \instruction[27] ;
  wire \instruction[28] ;
  wire \instruction[29] ;
  wire \instruction[2] ;
  wire \instruction[30] ;
  wire \instruction[31] ;
  wire \instruction[3] ;
  wire \instruction[4] ;
  wire \instruction[5] ;
  wire \instruction[6] ;
  wire \instruction[7] ;
  wire \instruction[8] ;
  wire \instruction[9] ;
  wire \instruction_IF[0] ;
  wire \instruction_IF[10] ;
  wire \instruction_IF[11] ;
  wire \instruction_IF[12] ;
  wire \instruction_IF[13] ;
  wire \instruction_IF[14] ;
  wire \instruction_IF[15] ;
  wire \instruction_IF[16] ;
  wire \instruction_IF[17] ;
  wire \instruction_IF[18] ;
  wire \instruction_IF[19] ;
  wire \instruction_IF[1] ;
  wire \instruction_IF[20] ;
  wire \instruction_IF[21] ;
  wire \instruction_IF[22] ;
  wire \instruction_IF[23] ;
  wire \instruction_IF[24] ;
  wire \instruction_IF[25] ;
  wire \instruction_IF[26] ;
  wire \instruction_IF[27] ;
  wire \instruction_IF[28] ;
  wire \instruction_IF[29] ;
  wire \instruction_IF[2] ;
  wire \instruction_IF[30] ;
  wire \instruction_IF[31] ;
  wire \instruction_IF[3] ;
  wire \instruction_IF[4] ;
  wire \instruction_IF[5] ;
  wire \instruction_IF[6] ;
  wire \instruction_IF[7] ;
  wire \instruction_IF[8] ;
  wire \instruction_IF[9] ;
  wire \isPC_select[0] ;
  wire \isPC_select[1] ;
  wire \isPC_select_ID[0] ;
  wire \isPC_select_ID[1] ;
  wire is_compressed;
  wire mul_active;
  wire \rdA[0] ;
  wire \rdA[10] ;
  wire \rdA[11] ;
  wire \rdA[12] ;
  wire \rdA[13] ;
  wire \rdA[14] ;
  wire \rdA[15] ;
  wire \rdA[16] ;
  wire \rdA[17] ;
  wire \rdA[18] ;
  wire \rdA[19] ;
  wire \rdA[1] ;
  wire \rdA[20] ;
  wire \rdA[21] ;
  wire \rdA[22] ;
  wire \rdA[23] ;
  wire \rdA[24] ;
  wire \rdA[25] ;
  wire \rdA[26] ;
  wire \rdA[27] ;
  wire \rdA[28] ;
  wire \rdA[29] ;
  wire \rdA[2] ;
  wire \rdA[30] ;
  wire \rdA[31] ;
  wire \rdA[3] ;
  wire \rdA[4] ;
  wire \rdA[5] ;
  wire \rdA[6] ;
  wire \rdA[7] ;
  wire \rdA[8] ;
  wire \rdA[9] ;
  wire \rdB[0] ;
  wire \rdB[10] ;
  wire \rdB[11] ;
  wire \rdB[12] ;
  wire \rdB[13] ;
  wire \rdB[14] ;
  wire \rdB[15] ;
  wire \rdB[16] ;
  wire \rdB[17] ;
  wire \rdB[18] ;
  wire \rdB[19] ;
  wire \rdB[1] ;
  wire \rdB[20] ;
  wire \rdB[21] ;
  wire \rdB[22] ;
  wire \rdB[23] ;
  wire \rdB[24] ;
  wire \rdB[25] ;
  wire \rdB[26] ;
  wire \rdB[27] ;
  wire \rdB[28] ;
  wire \rdB[29] ;
  wire \rdB[2] ;
  wire \rdB[30] ;
  wire \rdB[31] ;
  wire \rdB[3] ;
  wire \rdB[4] ;
  wire \rdB[5] ;
  wire \rdB[6] ;
  wire \rdB[7] ;
  wire \rdB[8] ;
  wire \rdB[9] ;
  wire \rdB_ForwB[0] ;
  wire \rdB_ForwB[10] ;
  wire \rdB_ForwB[11] ;
  wire \rdB_ForwB[12] ;
  wire \rdB_ForwB[13] ;
  wire \rdB_ForwB[14] ;
  wire \rdB_ForwB[15] ;
  wire \rdB_ForwB[16] ;
  wire \rdB_ForwB[17] ;
  wire \rdB_ForwB[18] ;
  wire \rdB_ForwB[19] ;
  wire \rdB_ForwB[1] ;
  wire \rdB_ForwB[20] ;
  wire \rdB_ForwB[21] ;
  wire \rdB_ForwB[22] ;
  wire \rdB_ForwB[23] ;
  wire \rdB_ForwB[24] ;
  wire \rdB_ForwB[25] ;
  wire \rdB_ForwB[26] ;
  wire \rdB_ForwB[27] ;
  wire \rdB_ForwB[28] ;
  wire \rdB_ForwB[29] ;
  wire \rdB_ForwB[2] ;
  wire \rdB_ForwB[30] ;
  wire \rdB_ForwB[31] ;
  wire \rdB_ForwB[3] ;
  wire \rdB_ForwB[4] ;
  wire \rdB_ForwB[5] ;
  wire \rdB_ForwB[6] ;
  wire \rdB_ForwB[7] ;
  wire \rdB_ForwB[8] ;
  wire \rdB_ForwB[9] ;
  wire \rd_EXMEM_MEM[0] ;
  wire \rd_EXMEM_MEM[1] ;
  wire \rd_EXMEM_MEM[2] ;
  wire \rd_EXMEM_MEM[3] ;
  wire \rd_EXMEM_MEM[4] ;
  wire \rd_ID[0] ;
  wire \rd_ID[1] ;
  wire \rd_ID[2] ;
  wire \rd_ID[3] ;
  wire \rd_ID[4] ;
  wire \rd_ID_EX_EX[0] ;
  wire \rd_ID_EX_EX[1] ;
  wire \rd_ID_EX_EX[2] ;
  wire \rd_ID_EX_EX[3] ;
  wire \rd_ID_EX_EX[4] ;
  wire \rf_data1[0] ;
  wire \rf_data1[10] ;
  wire \rf_data1[11] ;
  wire \rf_data1[12] ;
  wire \rf_data1[13] ;
  wire \rf_data1[14] ;
  wire \rf_data1[15] ;
  wire \rf_data1[16] ;
  wire \rf_data1[17] ;
  wire \rf_data1[18] ;
  wire \rf_data1[19] ;
  wire \rf_data1[1] ;
  wire \rf_data1[20] ;
  wire \rf_data1[21] ;
  wire \rf_data1[22] ;
  wire \rf_data1[23] ;
  wire \rf_data1[24] ;
  wire \rf_data1[25] ;
  wire \rf_data1[26] ;
  wire \rf_data1[27] ;
  wire \rf_data1[28] ;
  wire \rf_data1[29] ;
  wire \rf_data1[2] ;
  wire \rf_data1[30] ;
  wire \rf_data1[31] ;
  wire \rf_data1[3] ;
  wire \rf_data1[4] ;
  wire \rf_data1[5] ;
  wire \rf_data1[6] ;
  wire \rf_data1[7] ;
  wire \rf_data1[8] ;
  wire \rf_data1[9] ;
  wire \rf_data2[0] ;
  wire \rf_data2[10] ;
  wire \rf_data2[11] ;
  wire \rf_data2[12] ;
  wire \rf_data2[13] ;
  wire \rf_data2[14] ;
  wire \rf_data2[15] ;
  wire \rf_data2[16] ;
  wire \rf_data2[17] ;
  wire \rf_data2[18] ;
  wire \rf_data2[19] ;
  wire \rf_data2[1] ;
  wire \rf_data2[20] ;
  wire \rf_data2[21] ;
  wire \rf_data2[22] ;
  wire \rf_data2[23] ;
  wire \rf_data2[24] ;
  wire \rf_data2[25] ;
  wire \rf_data2[26] ;
  wire \rf_data2[27] ;
  wire \rf_data2[28] ;
  wire \rf_data2[29] ;
  wire \rf_data2[2] ;
  wire \rf_data2[30] ;
  wire \rf_data2[31] ;
  wire \rf_data2[3] ;
  wire \rf_data2[4] ;
  wire \rf_data2[5] ;
  wire \rf_data2[6] ;
  wire \rf_data2[7] ;
  wire \rf_data2[8] ;
  wire \rf_data2[9] ;
  wire \rs1_ID[0] ;
  wire \rs1_ID[1] ;
  wire \rs1_ID[2] ;
  wire \rs1_ID[3] ;
  wire \rs1_ID[4] ;
  wire \rs2_ID[0] ;
  wire \rs2_ID[1] ;
  wire \rs2_ID[2] ;
  wire \rs2_ID[3] ;
  wire \rs2_ID[4] ;
  wire rst;
  wire stall;
  wire stall_EX;
  wire stall_MEM;
  INV_X1 _262_ (
    .A(_042_),
    .ZN(_124_)
  );
  INV_X1 _263_ (
    .A(_007_),
    .ZN(_125_)
  );
  INV_X1 _264_ (
    .A(_002_),
    .ZN(_126_)
  );
  INV_X1 _265_ (
    .A(_008_),
    .ZN(_127_)
  );
  INV_X1 _266_ (
    .A(_216_),
    .ZN(_128_)
  );
  NOR2_X1 _267_ (
    .A1(_125_),
    .A2(_217_),
    .ZN(_046_)
  );
  NOR2_X1 _268_ (
    .A1(_126_),
    .A2(_217_),
    .ZN(_047_)
  );
  NOR2_X1 _269_ (
    .A1(_127_),
    .A2(_218_),
    .ZN(_044_)
  );
  OAI21_X1 _270_ (
    .A(_001_),
    .B1(_000_),
    .B2(_043_),
    .ZN(_129_)
  );
  AOI21_X1 _271_ (
    .A(_129_),
    .B1(_000_),
    .B2(_043_),
    .ZN(_045_)
  );
  NOR2_X1 _272_ (
    .A1(_041_),
    .A2(_124_),
    .ZN(_112_)
  );
  AND3_X1 _273_ (
    .A1(_041_),
    .A2(_124_),
    .A3(_005_),
    .ZN(_123_)
  );
  NOR3_X1 _274_ (
    .A1(_004_),
    .A2(_003_),
    .A3(_045_),
    .ZN(_130_)
  );
  NOR2_X1 _275_ (
    .A1(_128_),
    .A2(_130_),
    .ZN(_006_)
  );
  OR4_X1 _276_ (
    .A1(_147_),
    .A2(_148_),
    .A3(_149_),
    .A4(_151_),
    .ZN(_131_)
  );
  OAI21_X1 _277_ (
    .A(_008_),
    .B1(_150_),
    .B2(_131_),
    .ZN(_132_)
  );
  XOR2_X1 _278_ (
    .A(_151_),
    .B(_117_),
    .Z(_133_)
  );
  XNOR2_X1 _279_ (
    .A(_150_),
    .B(_116_),
    .ZN(_134_)
  );
  XNOR2_X1 _280_ (
    .A(_149_),
    .B(_115_),
    .ZN(_135_)
  );
  XOR2_X1 _281_ (
    .A(_147_),
    .B(_113_),
    .Z(_136_)
  );
  XNOR2_X1 _282_ (
    .A(_148_),
    .B(_114_),
    .ZN(_137_)
  );
  NAND3_X1 _283_ (
    .A1(_134_),
    .A2(_135_),
    .A3(_137_),
    .ZN(_138_)
  );
  NOR4_X1 _284_ (
    .A1(_132_),
    .A2(_133_),
    .A3(_136_),
    .A4(_138_),
    .ZN(_139_)
  );
  MUX2_X1 _285_ (
    .A(_152_),
    .B(_009_),
    .S(_139_),
    .Z(_048_)
  );
  MUX2_X1 _286_ (
    .A(_163_),
    .B(_020_),
    .S(_139_),
    .Z(_059_)
  );
  MUX2_X1 _287_ (
    .A(_174_),
    .B(_031_),
    .S(_139_),
    .Z(_070_)
  );
  MUX2_X1 _288_ (
    .A(_177_),
    .B(_034_),
    .S(_139_),
    .Z(_073_)
  );
  MUX2_X1 _289_ (
    .A(_178_),
    .B(_035_),
    .S(_139_),
    .Z(_074_)
  );
  MUX2_X1 _290_ (
    .A(_179_),
    .B(_036_),
    .S(_139_),
    .Z(_075_)
  );
  MUX2_X1 _291_ (
    .A(_180_),
    .B(_037_),
    .S(_139_),
    .Z(_076_)
  );
  MUX2_X1 _292_ (
    .A(_181_),
    .B(_038_),
    .S(_139_),
    .Z(_077_)
  );
  MUX2_X1 _293_ (
    .A(_182_),
    .B(_039_),
    .S(_139_),
    .Z(_078_)
  );
  MUX2_X1 _294_ (
    .A(_183_),
    .B(_040_),
    .S(_139_),
    .Z(_079_)
  );
  MUX2_X1 _295_ (
    .A(_153_),
    .B(_010_),
    .S(_139_),
    .Z(_049_)
  );
  MUX2_X1 _296_ (
    .A(_154_),
    .B(_011_),
    .S(_139_),
    .Z(_050_)
  );
  MUX2_X1 _297_ (
    .A(_155_),
    .B(_012_),
    .S(_139_),
    .Z(_051_)
  );
  MUX2_X1 _298_ (
    .A(_156_),
    .B(_013_),
    .S(_139_),
    .Z(_052_)
  );
  MUX2_X1 _299_ (
    .A(_157_),
    .B(_014_),
    .S(_139_),
    .Z(_053_)
  );
  MUX2_X1 _300_ (
    .A(_158_),
    .B(_015_),
    .S(_139_),
    .Z(_054_)
  );
  MUX2_X1 _301_ (
    .A(_159_),
    .B(_016_),
    .S(_139_),
    .Z(_055_)
  );
  MUX2_X1 _302_ (
    .A(_160_),
    .B(_017_),
    .S(_139_),
    .Z(_056_)
  );
  MUX2_X1 _303_ (
    .A(_161_),
    .B(_018_),
    .S(_139_),
    .Z(_057_)
  );
  MUX2_X1 _304_ (
    .A(_162_),
    .B(_019_),
    .S(_139_),
    .Z(_058_)
  );
  MUX2_X1 _305_ (
    .A(_164_),
    .B(_021_),
    .S(_139_),
    .Z(_060_)
  );
  MUX2_X1 _306_ (
    .A(_165_),
    .B(_022_),
    .S(_139_),
    .Z(_061_)
  );
  MUX2_X1 _307_ (
    .A(_166_),
    .B(_023_),
    .S(_139_),
    .Z(_062_)
  );
  MUX2_X1 _308_ (
    .A(_167_),
    .B(_024_),
    .S(_139_),
    .Z(_063_)
  );
  MUX2_X1 _309_ (
    .A(_168_),
    .B(_025_),
    .S(_139_),
    .Z(_064_)
  );
  MUX2_X1 _310_ (
    .A(_169_),
    .B(_026_),
    .S(_139_),
    .Z(_065_)
  );
  MUX2_X1 _311_ (
    .A(_170_),
    .B(_027_),
    .S(_139_),
    .Z(_066_)
  );
  MUX2_X1 _312_ (
    .A(_171_),
    .B(_028_),
    .S(_139_),
    .Z(_067_)
  );
  MUX2_X1 _313_ (
    .A(_172_),
    .B(_029_),
    .S(_139_),
    .Z(_068_)
  );
  MUX2_X1 _314_ (
    .A(_173_),
    .B(_030_),
    .S(_139_),
    .Z(_069_)
  );
  MUX2_X1 _315_ (
    .A(_175_),
    .B(_032_),
    .S(_139_),
    .Z(_071_)
  );
  MUX2_X1 _316_ (
    .A(_176_),
    .B(_033_),
    .S(_139_),
    .Z(_072_)
  );
  XOR2_X1 _317_ (
    .A(_150_),
    .B(_121_),
    .Z(_140_)
  );
  XNOR2_X1 _318_ (
    .A(_148_),
    .B(_119_),
    .ZN(_141_)
  );
  XNOR2_X1 _319_ (
    .A(_151_),
    .B(_122_),
    .ZN(_142_)
  );
  XNOR2_X1 _320_ (
    .A(_147_),
    .B(_118_),
    .ZN(_143_)
  );
  XNOR2_X1 _321_ (
    .A(_149_),
    .B(_120_),
    .ZN(_144_)
  );
  NAND4_X1 _322_ (
    .A1(_141_),
    .A2(_142_),
    .A3(_143_),
    .A4(_144_),
    .ZN(_145_)
  );
  NOR3_X1 _323_ (
    .A1(_132_),
    .A2(_140_),
    .A3(_145_),
    .ZN(_146_)
  );
  MUX2_X1 _324_ (
    .A(_184_),
    .B(_009_),
    .S(_146_),
    .Z(_080_)
  );
  MUX2_X1 _325_ (
    .A(_195_),
    .B(_020_),
    .S(_146_),
    .Z(_091_)
  );
  MUX2_X1 _326_ (
    .A(_206_),
    .B(_031_),
    .S(_146_),
    .Z(_102_)
  );
  MUX2_X1 _327_ (
    .A(_209_),
    .B(_034_),
    .S(_146_),
    .Z(_105_)
  );
  MUX2_X1 _328_ (
    .A(_210_),
    .B(_035_),
    .S(_146_),
    .Z(_106_)
  );
  MUX2_X1 _329_ (
    .A(_211_),
    .B(_036_),
    .S(_146_),
    .Z(_107_)
  );
  MUX2_X1 _330_ (
    .A(_212_),
    .B(_037_),
    .S(_146_),
    .Z(_108_)
  );
  MUX2_X1 _331_ (
    .A(_213_),
    .B(_038_),
    .S(_146_),
    .Z(_109_)
  );
  MUX2_X1 _332_ (
    .A(_214_),
    .B(_039_),
    .S(_146_),
    .Z(_110_)
  );
  MUX2_X1 _333_ (
    .A(_215_),
    .B(_040_),
    .S(_146_),
    .Z(_111_)
  );
  MUX2_X1 _334_ (
    .A(_185_),
    .B(_010_),
    .S(_146_),
    .Z(_081_)
  );
  MUX2_X1 _335_ (
    .A(_186_),
    .B(_011_),
    .S(_146_),
    .Z(_082_)
  );
  MUX2_X1 _336_ (
    .A(_187_),
    .B(_012_),
    .S(_146_),
    .Z(_083_)
  );
  MUX2_X1 _337_ (
    .A(_188_),
    .B(_013_),
    .S(_146_),
    .Z(_084_)
  );
  MUX2_X1 _338_ (
    .A(_189_),
    .B(_014_),
    .S(_146_),
    .Z(_085_)
  );
  MUX2_X1 _339_ (
    .A(_190_),
    .B(_015_),
    .S(_146_),
    .Z(_086_)
  );
  MUX2_X1 _340_ (
    .A(_191_),
    .B(_016_),
    .S(_146_),
    .Z(_087_)
  );
  MUX2_X1 _341_ (
    .A(_192_),
    .B(_017_),
    .S(_146_),
    .Z(_088_)
  );
  MUX2_X1 _342_ (
    .A(_193_),
    .B(_018_),
    .S(_146_),
    .Z(_089_)
  );
  MUX2_X1 _343_ (
    .A(_194_),
    .B(_019_),
    .S(_146_),
    .Z(_090_)
  );
  MUX2_X1 _344_ (
    .A(_196_),
    .B(_021_),
    .S(_146_),
    .Z(_092_)
  );
  MUX2_X1 _345_ (
    .A(_197_),
    .B(_022_),
    .S(_146_),
    .Z(_093_)
  );
  MUX2_X1 _346_ (
    .A(_198_),
    .B(_023_),
    .S(_146_),
    .Z(_094_)
  );
  MUX2_X1 _347_ (
    .A(_199_),
    .B(_024_),
    .S(_146_),
    .Z(_095_)
  );
  MUX2_X1 _348_ (
    .A(_200_),
    .B(_025_),
    .S(_146_),
    .Z(_096_)
  );
  MUX2_X1 _349_ (
    .A(_201_),
    .B(_026_),
    .S(_146_),
    .Z(_097_)
  );
  MUX2_X1 _350_ (
    .A(_202_),
    .B(_027_),
    .S(_146_),
    .Z(_098_)
  );
  MUX2_X1 _351_ (
    .A(_203_),
    .B(_028_),
    .S(_146_),
    .Z(_099_)
  );
  MUX2_X1 _352_ (
    .A(_204_),
    .B(_029_),
    .S(_146_),
    .Z(_100_)
  );
  MUX2_X1 _353_ (
    .A(_205_),
    .B(_030_),
    .S(_146_),
    .Z(_101_)
  );
  MUX2_X1 _354_ (
    .A(_207_),
    .B(_032_),
    .S(_146_),
    .Z(_103_)
  );
  MUX2_X1 _355_ (
    .A(_208_),
    .B(_033_),
    .S(_146_),
    .Z(_104_)
  );
  ALU ALU (
    .ALUControl({ \ALUControl_ID[4] , \ALUControl_ID[3] , \ALUControl_ID[2] , \ALUControl_ID[1] , \ALUControl_ID[0]  }),
    .ALUresult({ \ALUresult[31] , \ALUresult[30] , \ALUresult[29] , \ALUresult[28] , \ALUresult[27] , \ALUresult[26] , \ALUresult[25] , \ALUresult[24] , \ALUresult[23] , \ALUresult[22] , \ALUresult[21] , \ALUresult[20] , \ALUresult[19] , \ALUresult[18] , \ALUresult[17] , \ALUresult[16] , \ALUresult[15] , \ALUresult[14] , \ALUresult[13] , \ALUresult[12] , \ALUresult[11] , \ALUresult[10] , \ALUresult[9] , \ALUresult[8] , \ALUresult[7] , \ALUresult[6] , \ALUresult[5] , \ALUresult[4] , \ALUresult[3] , \ALUresult[2] , \ALUresult[1] , \ALUresult[0]  }),
    .Carry(Carry),
    .Zero(Zero),
    .clk(clk),
    .div_active(div_active),
    .mul_active(mul_active),
    .rdA({ \rdA[31] , \rdA[30] , \rdA[29] , \rdA[28] , \rdA[27] , \rdA[26] , \rdA[25] , \rdA[24] , \rdA[23] , \rdA[22] , \rdA[21] , \rdA[20] , \rdA[19] , \rdA[18] , \rdA[17] , \rdA[16] , \rdA[15] , \rdA[14] , \rdA[13] , \rdA[12] , \rdA[11] , \rdA[10] , \rdA[9] , \rdA[8] , \rdA[7] , \rdA[6] , \rdA[5] , \rdA[4] , \rdA[3] , \rdA[2] , \rdA[1] , \rdA[0]  }),
    .rdB({ \rdB[31] , \rdB[30] , \rdB[29] , \rdB[28] , \rdB[27] , \rdB[26] , \rdB[25] , \rdB[24] , \rdB[23] , \rdB[22] , \rdB[21] , \rdB[20] , \rdB[19] , \rdB[18] , \rdB[17] , \rdB[16] , \rdB[15] , \rdB[14] , \rdB[13] , \rdB[12] , \rdB[11] , \rdB[10] , \rdB[9] , \rdB[8] , \rdB[7] , \rdB[6] , \rdB[5] , \rdB[4] , \rdB[3] , \rdB[2] , \rdB[1] , \rdB[0]  }),
    .rst(rst)
  );
  Control_Unit Control_Unit (
    .ALUControl({ \ALUControl[4] , \ALUControl[3] , \ALUControl[2] , \ALUControl[1] , \ALUControl[0]  }),
    .ALUSrc(ALUSrc),
    .B_Zero(B_Zero),
    .Branch(Branch),
    .ImmType({ \ImmType[2] , \ImmType[1] , \ImmType[0]  }),
    .Jump(Jump),
    .JumpReg(JumpReg),
    .MemRead(MemRead),
    .MemWrite(MemWrite),
    .RegWrite(RegWrite),
    .ResultSrc({ \ResultSrc[1] , \ResultSrc[0]  }),
    .funct3({ \instruction_IF[14] , \instruction_IF[13] , \instruction_IF[12]  }),
    .funct7({ \instruction_IF[31] , \instruction_IF[30] , \instruction_IF[29] , \instruction_IF[28] , \instruction_IF[27] , \instruction_IF[26] , \instruction_IF[25]  }),
    .isPC_select({ \isPC_select[1] , \isPC_select[0]  }),
    .opcode({ \instruction_IF[6] , \instruction_IF[5] , \instruction_IF[4] , \instruction_IF[3] , \instruction_IF[2] , \instruction_IF[1] , \instruction_IF[0]  })
  );
  Ctrl_mux Ctrl_Mux (
    .ALUControl({ \ALUControl[4] , \ALUControl[3] , \ALUControl[2] , \ALUControl[1] , \ALUControl[0]  }),
    .ALUControlHZ({ \ALUControlHZ[4] , \ALUControlHZ[3] , \ALUControlHZ[2] , \ALUControlHZ[1] , \ALUControlHZ[0]  }),
    .ALUSrc(ALUSrc),
    .ALUSrcHZ(ALUSrcHZ),
    .Branch(Branch),
    .BranchHZ(BranchHZ),
    .Jump(Jump),
    .JumpHZ(JumpHZ),
    .JumpReg(JumpReg),
    .JumpRegHZ(JumpRegHZ),
    .MemRead(MemRead),
    .MemReadHZ(MemReadHZ),
    .MemWrite(MemWrite),
    .MemWriteHZ(MemWriteHZ),
    .RegWrite(RegWrite),
    .RegWriteHZ(RegWriteHZ),
    .ResultSrc({ \ResultSrc[1] , \ResultSrc[0]  }),
    .ResultSrcHZ({ \ResultSrcHZ[1] , \ResultSrcHZ[0]  }),
    .sel(NOP)
  );
  Data_Memory Data_Memory (
    .ALUresult({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .MemRead(\Mem_Con_EX[0] ),
    .MemWrite(_252_),
    .MemWriteData({ \data2_EX[31] , \data2_EX[30] , \data2_EX[29] , \data2_EX[28] , \data2_EX[27] , \data2_EX[26] , \data2_EX[25] , \data2_EX[24] , \data2_EX[23] , \data2_EX[22] , \data2_EX[21] , \data2_EX[20] , \data2_EX[19] , \data2_EX[18] , \data2_EX[17] , \data2_EX[16] , \data2_EX[15] , \data2_EX[14] , \data2_EX[13] , \data2_EX[12] , \data2_EX[11] , \data2_EX[10] , \data2_EX[9] , \data2_EX[8] , \data2_EX[7] , \data2_EX[6] , \data2_EX[5] , \data2_EX[4] , \data2_EX[3] , \data2_EX[2] , \data2_EX[1] , \data2_EX[0]  }),
    .PC({ \PC[31] , \PC[30] , \PC[29] , \PC[28] , \PC[27] , \PC[26] , \PC[25] , \PC[24] , \PC[23] , \PC[22] , \PC[21] , \PC[20] , \PC[19] , \PC[18] , \PC[17] , \PC[16] , \PC[15] , \PC[14] , \PC[13] , \PC[12] , \PC[11] , \PC[10] , \PC[9] , \PC[8] , \PC[7] , \PC[6] , \PC[5] , \PC[4] , \PC[3] , \PC[2]  }),
    .Rx_Data({ \FIFO_Rx_Dout[7] , \FIFO_Rx_Dout[6] , \FIFO_Rx_Dout[5] , \FIFO_Rx_Dout[4] , \FIFO_Rx_Dout[3] , \FIFO_Rx_Dout[2] , \FIFO_Rx_Dout[1] , \FIFO_Rx_Dout[0]  }),
    .Rx_read_en(Rx_read_en),
    .clk(clk),
    .empty_Rx(empty_Rx),
    .full_Rx(full_Rx),
    .portA({ \initial_instr[31] , \initial_instr[30] , \initial_instr[29] , \initial_instr[28] , \initial_instr[27] , \initial_instr[26] , \initial_instr[25] , \initial_instr[24] , \initial_instr[23] , \initial_instr[22] , \initial_instr[21] , \initial_instr[20] , \initial_instr[19] , \initial_instr[18] , \initial_instr[17] , \initial_instr[16] , \initial_instr[15] , \initial_instr[14] , \initial_instr[13] , \initial_instr[12] , \initial_instr[11] , \initial_instr[10] , \initial_instr[9] , \initial_instr[8] , \initial_instr[7] , \initial_instr[6] , \initial_instr[5] , \initial_instr[4] , \initial_instr[3] , \initial_instr[2] , \initial_instr[1] , \initial_instr[0]  }),
    .portB({ \MemReadData[31] , \MemReadData[30] , \MemReadData[29] , \MemReadData[28] , \MemReadData[27] , \MemReadData[26] , \MemReadData[25] , \MemReadData[24] , \MemReadData[23] , \MemReadData[22] , \MemReadData[21] , \MemReadData[20] , \MemReadData[19] , \MemReadData[18] , \MemReadData[17] , \MemReadData[16] , \MemReadData[15] , \MemReadData[14] , \MemReadData[13] , \MemReadData[12] , \MemReadData[11] , \MemReadData[10] , \MemReadData[9] , \MemReadData[8] , \MemReadData[7] , \MemReadData[6] , \MemReadData[5] , \MemReadData[4] , \MemReadData[3] , \MemReadData[2] , \MemReadData[1] , \MemReadData[0]  })
  );
  Decompressor_mux Decomp_Mux (
    .instr({ \initial_instr[1] , \initial_instr[0]  }),
    .is_compressed(is_compressed)
  );
  Decompressor Decompressor (
    .c_instr({ \initial_instr[15] , \initial_instr[14] , \initial_instr[13] , \initial_instr[12] , \initial_instr[11] , \initial_instr[10] , \initial_instr[9] , \initial_instr[8] , \initial_instr[7] , \initial_instr[6] , \initial_instr[5] , \initial_instr[4] , \initial_instr[3] , \initial_instr[2] , \initial_instr[1] , \initial_instr[0]  }),
    .r_instr({ \compress_instr[31] , \compress_instr[30] , \compress_instr[29] , \compress_instr[28] , \compress_instr[27] , \compress_instr[26] , \compress_instr[25] , \compress_instr[24] , \compress_instr[23] , \compress_instr[22] , \compress_instr[21] , \compress_instr[20] , \compress_instr[19] , \compress_instr[18] , \compress_instr[17] , \compress_instr[16] , \compress_instr[15] , \compress_instr[14] , \compress_instr[13] , \compress_instr[12] , \compress_instr[11] , \compress_instr[10] , \compress_instr[9] , \compress_instr[8] , \compress_instr[7] , \compress_instr[6] , \compress_instr[5] , \compress_instr[4] , \compress_instr[3] , \compress_instr[2] , \compress_instr[1] , \compress_instr[0]  })
  );
  EX_MEM EXMEM (
    .ALUresult({ \ALUresult[31] , \ALUresult[30] , \ALUresult[29] , \ALUresult[28] , \ALUresult[27] , \ALUresult[26] , \ALUresult[25] , \ALUresult[24] , \ALUresult[23] , \ALUresult[22] , \ALUresult[21] , \ALUresult[20] , \ALUresult[19] , \ALUresult[18] , \ALUresult[17] , \ALUresult[16] , \ALUresult[15] , \ALUresult[14] , \ALUresult[13] , \ALUresult[12] , \ALUresult[11] , \ALUresult[10] , \ALUresult[9] , \ALUresult[8] , \ALUresult[7] , \ALUresult[6] , \ALUresult[5] , \ALUresult[4] , \ALUresult[3] , \ALUresult[2] , \ALUresult[1] , \ALUresult[0]  }),
    .ALUresult_EX({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .Mem_Con({ \Mem_Con_ID[1] , \Mem_Con_ID[0]  }),
    .Mem_Con_EX({ \Mem_Con_EX[1] , \Mem_Con_EX[0]  }),
    .PC_next_EX({ \PC_next_EX[31] , \PC_next_EX[30] , \PC_next_EX[29] , \PC_next_EX[28] , \PC_next_EX[27] , \PC_next_EX[26] , \PC_next_EX[25] , \PC_next_EX[24] , \PC_next_EX[23] , \PC_next_EX[22] , \PC_next_EX[21] , \PC_next_EX[20] , \PC_next_EX[19] , \PC_next_EX[18] , \PC_next_EX[17] , \PC_next_EX[16] , \PC_next_EX[15] , \PC_next_EX[14] , \PC_next_EX[13] , \PC_next_EX[12] , \PC_next_EX[11] , \PC_next_EX[10] , \PC_next_EX[9] , \PC_next_EX[8] , \PC_next_EX[7] , \PC_next_EX[6] , \PC_next_EX[5] , \PC_next_EX[4] , \PC_next_EX[3] , \PC_next_EX[2] , \PC_next_EX[1] , \PC_next_EX[0]  }),
    .PC_next_ID({ \PC_next_ID[31] , \PC_next_ID[30] , \PC_next_ID[29] , \PC_next_ID[28] , \PC_next_ID[27] , \PC_next_ID[26] , \PC_next_ID[25] , \PC_next_ID[24] , \PC_next_ID[23] , \PC_next_ID[22] , \PC_next_ID[21] , \PC_next_ID[20] , \PC_next_ID[19] , \PC_next_ID[18] , \PC_next_ID[17] , \PC_next_ID[16] , \PC_next_ID[15] , \PC_next_ID[14] , \PC_next_ID[13] , \PC_next_ID[12] , \PC_next_ID[11] , \PC_next_ID[10] , \PC_next_ID[9] , \PC_next_ID[8] , \PC_next_ID[7] , \PC_next_ID[6] , \PC_next_ID[5] , \PC_next_ID[4] , \PC_next_ID[3] , \PC_next_ID[2] , \PC_next_ID[1] , \PC_next_ID[0]  }),
    .RegWrite(RegWrite_ID),
    .RegWrite_EX(RegWrite_EX),
    .ResultSrc({ \ResultSrc_ID[1] , \ResultSrc_ID[0]  }),
    .ResultSrc_EX({ \ResultSrc_EX[1] , \ResultSrc_EX[0]  }),
    .clk(clk),
    .data2({ \rdB_ForwB[31] , \rdB_ForwB[30] , \rdB_ForwB[29] , \rdB_ForwB[28] , \rdB_ForwB[27] , \rdB_ForwB[26] , \rdB_ForwB[25] , \rdB_ForwB[24] , \rdB_ForwB[23] , \rdB_ForwB[22] , \rdB_ForwB[21] , \rdB_ForwB[20] , \rdB_ForwB[19] , \rdB_ForwB[18] , \rdB_ForwB[17] , \rdB_ForwB[16] , \rdB_ForwB[15] , \rdB_ForwB[14] , \rdB_ForwB[13] , \rdB_ForwB[12] , \rdB_ForwB[11] , \rdB_ForwB[10] , \rdB_ForwB[9] , \rdB_ForwB[8] , \rdB_ForwB[7] , \rdB_ForwB[6] , \rdB_ForwB[5] , \rdB_ForwB[4] , \rdB_ForwB[3] , \rdB_ForwB[2] , \rdB_ForwB[1] , \rdB_ForwB[0]  }),
    .data2_EX({ \data2_EX[31] , \data2_EX[30] , \data2_EX[29] , \data2_EX[28] , \data2_EX[27] , \data2_EX[26] , \data2_EX[25] , \data2_EX[24] , \data2_EX[23] , \data2_EX[22] , \data2_EX[21] , \data2_EX[20] , \data2_EX[19] , \data2_EX[18] , \data2_EX[17] , \data2_EX[16] , \data2_EX[15] , \data2_EX[14] , \data2_EX[13] , \data2_EX[12] , \data2_EX[11] , \data2_EX[10] , \data2_EX[9] , \data2_EX[8] , \data2_EX[7] , \data2_EX[6] , \data2_EX[5] , \data2_EX[4] , \data2_EX[3] , \data2_EX[2] , \data2_EX[1] , \data2_EX[0]  }),
    .rd_ID_EX({ \rd_ID[4] , \rd_ID[3] , \rd_ID[2] , \rd_ID[1] , \rd_ID[0]  }),
    .rd_ID_EX_EX({ \rd_ID_EX_EX[4] , \rd_ID_EX_EX[3] , \rd_ID_EX_EX[2] , \rd_ID_EX_EX[1] , \rd_ID_EX_EX[0]  }),
    .rst(rst),
    .stall(stall),
    .stall_EX(stall_EX)
  );
  Forwarding_Block FB (
    .EX_MEM_RegWrite(RegWrite_EX),
    .EX_MEM_rd({ \rd_ID_EX_EX[4] , \rd_ID_EX_EX[3] , \rd_ID_EX_EX[2] , \rd_ID_EX_EX[1] , \rd_ID_EX_EX[0]  }),
    .ForwardA({ \ForwardA[1] , \ForwardA[0]  }),
    .ForwardB({ \ForwardB[1] , \ForwardB[0]  }),
    .ID_EX_rs1({ \rs1_ID[4] , \rs1_ID[3] , \rs1_ID[2] , \rs1_ID[1] , \rs1_ID[0]  }),
    .ID_EX_rs2({ \rs2_ID[4] , \rs2_ID[3] , \rs2_ID[2] , \rs2_ID[1] , \rs2_ID[0]  }),
    .MEM_WB_RegWrite(RegWrite_MEM),
    .MEM_WB_rd({ \rd_EXMEM_MEM[4] , \rd_EXMEM_MEM[3] , \rd_EXMEM_MEM[2] , \rd_EXMEM_MEM[1] , \rd_EXMEM_MEM[0]  })
  );
  FourXone_mux ForwA_mux (
    .A({ \data1_ID[31] , \data1_ID[30] , \data1_ID[29] , \data1_ID[28] , \data1_ID[27] , \data1_ID[26] , \data1_ID[25] , \data1_ID[24] , \data1_ID[23] , \data1_ID[22] , \data1_ID[21] , \data1_ID[20] , \data1_ID[19] , \data1_ID[18] , \data1_ID[17] , \data1_ID[16] , \data1_ID[15] , \data1_ID[14] , \data1_ID[13] , \data1_ID[12] , \data1_ID[11] , \data1_ID[10] , \data1_ID[9] , \data1_ID[8] , \data1_ID[7] , \data1_ID[6] , \data1_ID[5] , \data1_ID[4] , \data1_ID[3] , \data1_ID[2] , \data1_ID[1] , \data1_ID[0]  }),
    .B({ \Result[31] , \Result[30] , \Result[29] , \Result[28] , \Result[27] , \Result[26] , \Result[25] , \Result[24] , \Result[23] , \Result[22] , \Result[21] , \Result[20] , \Result[19] , \Result[18] , \Result[17] , \Result[16] , \Result[15] , \Result[14] , \Result[13] , \Result[12] , \Result[11] , \Result[10] , \Result[9] , \Result[8] , \Result[7] , \Result[6] , \Result[5] , \Result[4] , \Result[3] , \Result[2] , \Result[1] , \Result[0]  }),
    .C({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .Out({ \data1_ID_ForwA[31] , \data1_ID_ForwA[30] , \data1_ID_ForwA[29] , \data1_ID_ForwA[28] , \data1_ID_ForwA[27] , \data1_ID_ForwA[26] , \data1_ID_ForwA[25] , \data1_ID_ForwA[24] , \data1_ID_ForwA[23] , \data1_ID_ForwA[22] , \data1_ID_ForwA[21] , \data1_ID_ForwA[20] , \data1_ID_ForwA[19] , \data1_ID_ForwA[18] , \data1_ID_ForwA[17] , \data1_ID_ForwA[16] , \data1_ID_ForwA[15] , \data1_ID_ForwA[14] , \data1_ID_ForwA[13] , \data1_ID_ForwA[12] , \data1_ID_ForwA[11] , \data1_ID_ForwA[10] , \data1_ID_ForwA[9] , \data1_ID_ForwA[8] , \data1_ID_ForwA[7] , \data1_ID_ForwA[6] , \data1_ID_ForwA[5] , \data1_ID_ForwA[4] , \data1_ID_ForwA[3] , \data1_ID_ForwA[2] , \data1_ID_ForwA[1] , \data1_ID_ForwA[0]  }),
    .sel({ \ForwardA[1] , \ForwardA[0]  })
  );
  FourXone_mux ForwB_mux (
    .A({ \data2_ID[31] , \data2_ID[30] , \data2_ID[29] , \data2_ID[28] , \data2_ID[27] , \data2_ID[26] , \data2_ID[25] , \data2_ID[24] , \data2_ID[23] , \data2_ID[22] , \data2_ID[21] , \data2_ID[20] , \data2_ID[19] , \data2_ID[18] , \data2_ID[17] , \data2_ID[16] , \data2_ID[15] , \data2_ID[14] , \data2_ID[13] , \data2_ID[12] , \data2_ID[11] , \data2_ID[10] , \data2_ID[9] , \data2_ID[8] , \data2_ID[7] , \data2_ID[6] , \data2_ID[5] , \data2_ID[4] , \data2_ID[3] , \data2_ID[2] , \data2_ID[1] , \data2_ID[0]  }),
    .B({ \Result[31] , \Result[30] , \Result[29] , \Result[28] , \Result[27] , \Result[26] , \Result[25] , \Result[24] , \Result[23] , \Result[22] , \Result[21] , \Result[20] , \Result[19] , \Result[18] , \Result[17] , \Result[16] , \Result[15] , \Result[14] , \Result[13] , \Result[12] , \Result[11] , \Result[10] , \Result[9] , \Result[8] , \Result[7] , \Result[6] , \Result[5] , \Result[4] , \Result[3] , \Result[2] , \Result[1] , \Result[0]  }),
    .C({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .Out({ \rdB_ForwB[31] , \rdB_ForwB[30] , \rdB_ForwB[29] , \rdB_ForwB[28] , \rdB_ForwB[27] , \rdB_ForwB[26] , \rdB_ForwB[25] , \rdB_ForwB[24] , \rdB_ForwB[23] , \rdB_ForwB[22] , \rdB_ForwB[21] , \rdB_ForwB[20] , \rdB_ForwB[19] , \rdB_ForwB[18] , \rdB_ForwB[17] , \rdB_ForwB[16] , \rdB_ForwB[15] , \rdB_ForwB[14] , \rdB_ForwB[13] , \rdB_ForwB[12] , \rdB_ForwB[11] , \rdB_ForwB[10] , \rdB_ForwB[9] , \rdB_ForwB[8] , \rdB_ForwB[7] , \rdB_ForwB[6] , \rdB_ForwB[5] , \rdB_ForwB[4] , \rdB_ForwB[3] , \rdB_ForwB[2] , \rdB_ForwB[1] , \rdB_ForwB[0]  }),
    .sel({ \ForwardB[1] , \ForwardB[0]  })
  );
  Hazard_Detection Haz_Det (
    .Branch(_220_),
    .Flush(Flush),
    .ID_EX_MemRead(\Mem_Con_ID[0] ),
    .ID_EX_rd({ \rd_ID[4] , \rd_ID[3] , \rd_ID[2] , \rd_ID[1] , \rd_ID[0]  }),
    .IF_ID_WriteEN(IF_ID_WriteEN),
    .IF_ID_rs1({ \instruction_IF[19] , \instruction_IF[18] , \instruction_IF[17] , \instruction_IF[16] , \instruction_IF[15]  }),
    .IF_ID_rs2({ \instruction_IF[24] , \instruction_IF[23] , \instruction_IF[22] , \instruction_IF[21] , \instruction_IF[20]  }),
    .Jump(Jump_ID),
    .JumpReg(JumpReg_ID),
    .NOP(NOP),
    .PCWriteEN(PCWriteEN)
  );
  ID_EX IDEX (
    .ALUControlHZ({ \ALUControlHZ[4] , \ALUControlHZ[3] , \ALUControlHZ[2] , \ALUControlHZ[1] , \ALUControlHZ[0]  }),
    .ALUControl_ID({ \ALUControl_ID[4] , \ALUControl_ID[3] , \ALUControl_ID[2] , \ALUControl_ID[1] , \ALUControl_ID[0]  }),
    .ALUSrc(ALUSrcHZ),
    .ALUSrc_ID(ALUSrc_ID),
    .B_Zero(B_Zero),
    .B_Zero_ID(B_Zero_ID),
    .BranchHZ(BranchHZ),
    .Branch_ID(Branch_ID),
    .Flush(Flush),
    .ImmExt({ \ImmExt[31] , \ImmExt[30] , \ImmExt[29] , \ImmExt[28] , \ImmExt[27] , \ImmExt[26] , \ImmExt[25] , \ImmExt[24] , \ImmExt[23] , \ImmExt[22] , \ImmExt[21] , \ImmExt[20] , \ImmExt[19] , \ImmExt[18] , \ImmExt[17] , \ImmExt[16] , \ImmExt[15] , \ImmExt[14] , \ImmExt[13] , \ImmExt[12] , \ImmExt[11] , \ImmExt[10] , \ImmExt[9] , \ImmExt[8] , \ImmExt[7] , \ImmExt[6] , \ImmExt[5] , \ImmExt[4] , \ImmExt[3] , \ImmExt[2] , \ImmExt[1] , \ImmExt[0]  }),
    .ImmExt_ID({ \ImmExt_ID[31] , \ImmExt_ID[30] , \ImmExt_ID[29] , \ImmExt_ID[28] , \ImmExt_ID[27] , \ImmExt_ID[26] , \ImmExt_ID[25] , \ImmExt_ID[24] , \ImmExt_ID[23] , \ImmExt_ID[22] , \ImmExt_ID[21] , \ImmExt_ID[20] , \ImmExt_ID[19] , \ImmExt_ID[18] , \ImmExt_ID[17] , \ImmExt_ID[16] , \ImmExt_ID[15] , \ImmExt_ID[14] , \ImmExt_ID[13] , \ImmExt_ID[12] , \ImmExt_ID[11] , \ImmExt_ID[10] , \ImmExt_ID[9] , \ImmExt_ID[8] , \ImmExt_ID[7] , \ImmExt_ID[6] , \ImmExt_ID[5] , \ImmExt_ID[4] , \ImmExt_ID[3] , \ImmExt_ID[2] , \ImmExt_ID[1] , \ImmExt_ID[0]  }),
    .JumpHZ(JumpHZ),
    .JumpRegHZ(JumpRegHZ),
    .JumpReg_ID(JumpReg_ID),
    .Jump_ID(Jump_ID),
    .Mem_Con({ MemWriteHZ, MemReadHZ }),
    .Mem_Con_ID({ \Mem_Con_ID[1] , \Mem_Con_ID[0]  }),
    .PC({ \PC_IF[31] , \PC_IF[30] , \PC_IF[29] , \PC_IF[28] , \PC_IF[27] , \PC_IF[26] , \PC_IF[25] , \PC_IF[24] , \PC_IF[23] , \PC_IF[22] , \PC_IF[21] , \PC_IF[20] , \PC_IF[19] , \PC_IF[18] , \PC_IF[17] , \PC_IF[16] , \PC_IF[15] , \PC_IF[14] , \PC_IF[13] , \PC_IF[12] , \PC_IF[11] , \PC_IF[10] , \PC_IF[9] , \PC_IF[8] , \PC_IF[7] , \PC_IF[6] , \PC_IF[5] , \PC_IF[4] , \PC_IF[3] , \PC_IF[2] , \PC_IF[1] , \PC_IF[0]  }),
    .PC_ID({ \PC_ID[31] , \PC_ID[30] , \PC_ID[29] , \PC_ID[28] , \PC_ID[27] , \PC_ID[26] , \PC_ID[25] , \PC_ID[24] , \PC_ID[23] , \PC_ID[22] , \PC_ID[21] , \PC_ID[20] , \PC_ID[19] , \PC_ID[18] , \PC_ID[17] , \PC_ID[16] , \PC_ID[15] , \PC_ID[14] , \PC_ID[13] , \PC_ID[12] , \PC_ID[11] , \PC_ID[10] , \PC_ID[9] , \PC_ID[8] , \PC_ID[7] , \PC_ID[6] , \PC_ID[5] , \PC_ID[4] , \PC_ID[3] , \PC_ID[2] , \PC_ID[1] , \PC_ID[0]  }),
    .PC_next_ID({ \PC_next_ID[31] , \PC_next_ID[30] , \PC_next_ID[29] , \PC_next_ID[28] , \PC_next_ID[27] , \PC_next_ID[26] , \PC_next_ID[25] , \PC_next_ID[24] , \PC_next_ID[23] , \PC_next_ID[22] , \PC_next_ID[21] , \PC_next_ID[20] , \PC_next_ID[19] , \PC_next_ID[18] , \PC_next_ID[17] , \PC_next_ID[16] , \PC_next_ID[15] , \PC_next_ID[14] , \PC_next_ID[13] , \PC_next_ID[12] , \PC_next_ID[11] , \PC_next_ID[10] , \PC_next_ID[9] , \PC_next_ID[8] , \PC_next_ID[7] , \PC_next_ID[6] , \PC_next_ID[5] , \PC_next_ID[4] , \PC_next_ID[3] , \PC_next_ID[2] , \PC_next_ID[1] , \PC_next_ID[0]  }),
    .PC_next_IF({ \PC_next_IF[31] , \PC_next_IF[30] , \PC_next_IF[29] , \PC_next_IF[28] , \PC_next_IF[27] , \PC_next_IF[26] , \PC_next_IF[25] , \PC_next_IF[24] , \PC_next_IF[23] , \PC_next_IF[22] , \PC_next_IF[21] , \PC_next_IF[20] , \PC_next_IF[19] , \PC_next_IF[18] , \PC_next_IF[17] , \PC_next_IF[16] , \PC_next_IF[15] , \PC_next_IF[14] , \PC_next_IF[13] , \PC_next_IF[12] , \PC_next_IF[11] , \PC_next_IF[10] , \PC_next_IF[9] , \PC_next_IF[8] , \PC_next_IF[7] , \PC_next_IF[6] , \PC_next_IF[5] , \PC_next_IF[4] , \PC_next_IF[3] , \PC_next_IF[2] , \PC_next_IF[1] , \PC_next_IF[0]  }),
    .RegWrite(RegWriteHZ),
    .RegWrite_ID(RegWrite_ID),
    .ResultSrcHZ({ \ResultSrcHZ[1] , \ResultSrcHZ[0]  }),
    .ResultSrc_ID({ \ResultSrc_ID[1] , \ResultSrc_ID[0]  }),
    .clk(clk),
    .data1({ \data1[31] , \data1[30] , \data1[29] , \data1[28] , \data1[27] , \data1[26] , \data1[25] , \data1[24] , \data1[23] , \data1[22] , \data1[21] , \data1[20] , \data1[19] , \data1[18] , \data1[17] , \data1[16] , \data1[15] , \data1[14] , \data1[13] , \data1[12] , \data1[11] , \data1[10] , \data1[9] , \data1[8] , \data1[7] , \data1[6] , \data1[5] , \data1[4] , \data1[3] , \data1[2] , \data1[1] , \data1[0]  }),
    .data1_ID({ \data1_ID[31] , \data1_ID[30] , \data1_ID[29] , \data1_ID[28] , \data1_ID[27] , \data1_ID[26] , \data1_ID[25] , \data1_ID[24] , \data1_ID[23] , \data1_ID[22] , \data1_ID[21] , \data1_ID[20] , \data1_ID[19] , \data1_ID[18] , \data1_ID[17] , \data1_ID[16] , \data1_ID[15] , \data1_ID[14] , \data1_ID[13] , \data1_ID[12] , \data1_ID[11] , \data1_ID[10] , \data1_ID[9] , \data1_ID[8] , \data1_ID[7] , \data1_ID[6] , \data1_ID[5] , \data1_ID[4] , \data1_ID[3] , \data1_ID[2] , \data1_ID[1] , \data1_ID[0]  }),
    .data2({ \data2[31] , \data2[30] , \data2[29] , \data2[28] , \data2[27] , \data2[26] , \data2[25] , \data2[24] , \data2[23] , \data2[22] , \data2[21] , \data2[20] , \data2[19] , \data2[18] , \data2[17] , \data2[16] , \data2[15] , \data2[14] , \data2[13] , \data2[12] , \data2[11] , \data2[10] , \data2[9] , \data2[8] , \data2[7] , \data2[6] , \data2[5] , \data2[4] , \data2[3] , \data2[2] , \data2[1] , \data2[0]  }),
    .data2_ID({ \data2_ID[31] , \data2_ID[30] , \data2_ID[29] , \data2_ID[28] , \data2_ID[27] , \data2_ID[26] , \data2_ID[25] , \data2_ID[24] , \data2_ID[23] , \data2_ID[22] , \data2_ID[21] , \data2_ID[20] , \data2_ID[19] , \data2_ID[18] , \data2_ID[17] , \data2_ID[16] , \data2_ID[15] , \data2_ID[14] , \data2_ID[13] , \data2_ID[12] , \data2_ID[11] , \data2_ID[10] , \data2_ID[9] , \data2_ID[8] , \data2_ID[7] , \data2_ID[6] , \data2_ID[5] , \data2_ID[4] , \data2_ID[3] , \data2_ID[2] , \data2_ID[1] , \data2_ID[0]  }),
    .isPC_select({ \isPC_select[1] , \isPC_select[0]  }),
    .isPC_select_ID({ \isPC_select_ID[1] , \isPC_select_ID[0]  }),
    .rd({ \instruction_IF[11] , \instruction_IF[10] , \instruction_IF[9] , \instruction_IF[8] , \instruction_IF[7]  }),
    .rd_ID({ \rd_ID[4] , \rd_ID[3] , \rd_ID[2] , \rd_ID[1] , \rd_ID[0]  }),
    .rs1({ \instruction_IF[19] , \instruction_IF[18] , \instruction_IF[17] , \instruction_IF[16] , \instruction_IF[15]  }),
    .rs1_ID({ \rs1_ID[4] , \rs1_ID[3] , \rs1_ID[2] , \rs1_ID[1] , \rs1_ID[0]  }),
    .rs2({ \instruction_IF[24] , \instruction_IF[23] , \instruction_IF[22] , \instruction_IF[21] , \instruction_IF[20]  }),
    .rs2_ID({ \rs2_ID[4] , \rs2_ID[3] , \rs2_ID[2] , \rs2_ID[1] , \rs2_ID[0]  }),
    .rst(rst),
    .stall(stall)
  );
  IF_ID IFID (
    .Flush(Flush),
    .IF_ID_WriteEN(_222_),
    .PC({ \PC[31] , \PC[30] , \PC[29] , \PC[28] , \PC[27] , \PC[26] , \PC[25] , \PC[24] , \PC[23] , \PC[22] , \PC[21] , \PC[20] , \PC[19] , \PC[18] , \PC[17] , \PC[16] , \PC[15] , \PC[14] , \PC[13] , \PC[12] , \PC[11] , \PC[10] , \PC[9] , \PC[8] , \PC[7] , \PC[6] , \PC[5] , \PC[4] , \PC[3] , \PC[2] , \PC[1] , \PC[0]  }),
    .PC_IF({ \PC_IF[31] , \PC_IF[30] , \PC_IF[29] , \PC_IF[28] , \PC_IF[27] , \PC_IF[26] , \PC_IF[25] , \PC_IF[24] , \PC_IF[23] , \PC_IF[22] , \PC_IF[21] , \PC_IF[20] , \PC_IF[19] , \PC_IF[18] , \PC_IF[17] , \PC_IF[16] , \PC_IF[15] , \PC_IF[14] , \PC_IF[13] , \PC_IF[12] , \PC_IF[11] , \PC_IF[10] , \PC_IF[9] , \PC_IF[8] , \PC_IF[7] , \PC_IF[6] , \PC_IF[5] , \PC_IF[4] , \PC_IF[3] , \PC_IF[2] , \PC_IF[1] , \PC_IF[0]  }),
    .PC_next({ \PC_next[31] , \PC_next[30] , \PC_next[29] , \PC_next[28] , \PC_next[27] , \PC_next[26] , \PC_next[25] , \PC_next[24] , \PC_next[23] , \PC_next[22] , \PC_next[21] , \PC_next[20] , \PC_next[19] , \PC_next[18] , \PC_next[17] , \PC_next[16] , \PC_next[15] , \PC_next[14] , \PC_next[13] , \PC_next[12] , \PC_next[11] , \PC_next[10] , \PC_next[9] , \PC_next[8] , \PC_next[7] , \PC_next[6] , \PC_next[5] , \PC_next[4] , \PC_next[3] , \PC_next[2] , \PC_next[1] , \PC_next[0]  }),
    .PC_next_IF({ \PC_next_IF[31] , \PC_next_IF[30] , \PC_next_IF[29] , \PC_next_IF[28] , \PC_next_IF[27] , \PC_next_IF[26] , \PC_next_IF[25] , \PC_next_IF[24] , \PC_next_IF[23] , \PC_next_IF[22] , \PC_next_IF[21] , \PC_next_IF[20] , \PC_next_IF[19] , \PC_next_IF[18] , \PC_next_IF[17] , \PC_next_IF[16] , \PC_next_IF[15] , \PC_next_IF[14] , \PC_next_IF[13] , \PC_next_IF[12] , \PC_next_IF[11] , \PC_next_IF[10] , \PC_next_IF[9] , \PC_next_IF[8] , \PC_next_IF[7] , \PC_next_IF[6] , \PC_next_IF[5] , \PC_next_IF[4] , \PC_next_IF[3] , \PC_next_IF[2] , \PC_next_IF[1] , \PC_next_IF[0]  }),
    .clk(clk),
    .instruction({ \instruction[31] , \instruction[30] , \instruction[29] , \instruction[28] , \instruction[27] , \instruction[26] , \instruction[25] , \instruction[24] , \instruction[23] , \instruction[22] , \instruction[21] , \instruction[20] , \instruction[19] , \instruction[18] , \instruction[17] , \instruction[16] , \instruction[15] , \instruction[14] , \instruction[13] , \instruction[12] , \instruction[11] , \instruction[10] , \instruction[9] , \instruction[8] , \instruction[7] , \instruction[6] , \instruction[5] , \instruction[4] , \instruction[3] , \instruction[2] , \instruction[1] , \instruction[0]  }),
    .instruction_IF({ \instruction_IF[31] , \instruction_IF[30] , \instruction_IF[29] , \instruction_IF[28] , \instruction_IF[27] , \instruction_IF[26] , \instruction_IF[25] , \instruction_IF[24] , \instruction_IF[23] , \instruction_IF[22] , \instruction_IF[21] , \instruction_IF[20] , \instruction_IF[19] , \instruction_IF[18] , \instruction_IF[17] , \instruction_IF[16] , \instruction_IF[15] , \instruction_IF[14] , \instruction_IF[13] , \instruction_IF[12] , \instruction_IF[11] , \instruction_IF[10] , \instruction_IF[9] , \instruction_IF[8] , \instruction_IF[7] , \instruction_IF[6] , \instruction_IF[5] , \instruction_IF[4] , \instruction_IF[3] , \instruction_IF[2] , \instruction_IF[1] , \instruction_IF[0]  }),
    .rst(rst)
  );
  Imm_Extend Imm0 (
    .ImmExt({ \ImmExt[31] , \ImmExt[30] , \ImmExt[29] , \ImmExt[28] , \ImmExt[27] , \ImmExt[26] , \ImmExt[25] , \ImmExt[24] , \ImmExt[23] , \ImmExt[22] , \ImmExt[21] , \ImmExt[20] , \ImmExt[19] , \ImmExt[18] , \ImmExt[17] , \ImmExt[16] , \ImmExt[15] , \ImmExt[14] , \ImmExt[13] , \ImmExt[12] , \ImmExt[11] , \ImmExt[10] , \ImmExt[9] , \ImmExt[8] , \ImmExt[7] , \ImmExt[6] , \ImmExt[5] , \ImmExt[4] , \ImmExt[3] , \ImmExt[2] , \ImmExt[1] , \ImmExt[0]  }),
    .ImmType({ \ImmType[2] , \ImmType[1] , \ImmType[0]  }),
    .instruction({ \instruction_IF[31] , \instruction_IF[30] , \instruction_IF[29] , \instruction_IF[28] , \instruction_IF[27] , \instruction_IF[26] , \instruction_IF[25] , \instruction_IF[24] , \instruction_IF[23] , \instruction_IF[22] , \instruction_IF[21] , \instruction_IF[20] , \instruction_IF[19] , \instruction_IF[18] , \instruction_IF[17] , \instruction_IF[16] , \instruction_IF[15] , \instruction_IF[14] , \instruction_IF[13] , \instruction_IF[12] , \instruction_IF[11] , \instruction_IF[10] , \instruction_IF[9] , \instruction_IF[8] , \instruction_IF[7]  })
  );
  MEM_WB MEMWB (
    .ALUresult({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .ALUresult_MEM({ \ALUresult_MEM[31] , \ALUresult_MEM[30] , \ALUresult_MEM[29] , \ALUresult_MEM[28] , \ALUresult_MEM[27] , \ALUresult_MEM[26] , \ALUresult_MEM[25] , \ALUresult_MEM[24] , \ALUresult_MEM[23] , \ALUresult_MEM[22] , \ALUresult_MEM[21] , \ALUresult_MEM[20] , \ALUresult_MEM[19] , \ALUresult_MEM[18] , \ALUresult_MEM[17] , \ALUresult_MEM[16] , \ALUresult_MEM[15] , \ALUresult_MEM[14] , \ALUresult_MEM[13] , \ALUresult_MEM[12] , \ALUresult_MEM[11] , \ALUresult_MEM[10] , \ALUresult_MEM[9] , \ALUresult_MEM[8] , \ALUresult_MEM[7] , \ALUresult_MEM[6] , \ALUresult_MEM[5] , \ALUresult_MEM[4] , \ALUresult_MEM[3] , \ALUresult_MEM[2] , \ALUresult_MEM[1] , \ALUresult_MEM[0]  }),
    .MemReadData({ \MemReadData[31] , \MemReadData[30] , \MemReadData[29] , \MemReadData[28] , \MemReadData[27] , \MemReadData[26] , \MemReadData[25] , \MemReadData[24] , \MemReadData[23] , \MemReadData[22] , \MemReadData[21] , \MemReadData[20] , \MemReadData[19] , \MemReadData[18] , \MemReadData[17] , \MemReadData[16] , \MemReadData[15] , \MemReadData[14] , \MemReadData[13] , \MemReadData[12] , \MemReadData[11] , \MemReadData[10] , \MemReadData[9] , \MemReadData[8] , \MemReadData[7] , \MemReadData[6] , \MemReadData[5] , \MemReadData[4] , \MemReadData[3] , \MemReadData[2] , \MemReadData[1] , \MemReadData[0]  }),
    .MemReadData_MEM({ \MemReadData_MEM[31] , \MemReadData_MEM[30] , \MemReadData_MEM[29] , \MemReadData_MEM[28] , \MemReadData_MEM[27] , \MemReadData_MEM[26] , \MemReadData_MEM[25] , \MemReadData_MEM[24] , \MemReadData_MEM[23] , \MemReadData_MEM[22] , \MemReadData_MEM[21] , \MemReadData_MEM[20] , \MemReadData_MEM[19] , \MemReadData_MEM[18] , \MemReadData_MEM[17] , \MemReadData_MEM[16] , \MemReadData_MEM[15] , \MemReadData_MEM[14] , \MemReadData_MEM[13] , \MemReadData_MEM[12] , \MemReadData_MEM[11] , \MemReadData_MEM[10] , \MemReadData_MEM[9] , \MemReadData_MEM[8] , \MemReadData_MEM[7] , \MemReadData_MEM[6] , \MemReadData_MEM[5] , \MemReadData_MEM[4] , \MemReadData_MEM[3] , \MemReadData_MEM[2] , \MemReadData_MEM[1] , \MemReadData_MEM[0]  }),
    .PC_next_EX({ \PC_next_EX[31] , \PC_next_EX[30] , \PC_next_EX[29] , \PC_next_EX[28] , \PC_next_EX[27] , \PC_next_EX[26] , \PC_next_EX[25] , \PC_next_EX[24] , \PC_next_EX[23] , \PC_next_EX[22] , \PC_next_EX[21] , \PC_next_EX[20] , \PC_next_EX[19] , \PC_next_EX[18] , \PC_next_EX[17] , \PC_next_EX[16] , \PC_next_EX[15] , \PC_next_EX[14] , \PC_next_EX[13] , \PC_next_EX[12] , \PC_next_EX[11] , \PC_next_EX[10] , \PC_next_EX[9] , \PC_next_EX[8] , \PC_next_EX[7] , \PC_next_EX[6] , \PC_next_EX[5] , \PC_next_EX[4] , \PC_next_EX[3] , \PC_next_EX[2] , \PC_next_EX[1] , \PC_next_EX[0]  }),
    .PC_next_MEM({ \PC_next_MEM[31] , \PC_next_MEM[30] , \PC_next_MEM[29] , \PC_next_MEM[28] , \PC_next_MEM[27] , \PC_next_MEM[26] , \PC_next_MEM[25] , \PC_next_MEM[24] , \PC_next_MEM[23] , \PC_next_MEM[22] , \PC_next_MEM[21] , \PC_next_MEM[20] , \PC_next_MEM[19] , \PC_next_MEM[18] , \PC_next_MEM[17] , \PC_next_MEM[16] , \PC_next_MEM[15] , \PC_next_MEM[14] , \PC_next_MEM[13] , \PC_next_MEM[12] , \PC_next_MEM[11] , \PC_next_MEM[10] , \PC_next_MEM[9] , \PC_next_MEM[8] , \PC_next_MEM[7] , \PC_next_MEM[6] , \PC_next_MEM[5] , \PC_next_MEM[4] , \PC_next_MEM[3] , \PC_next_MEM[2] , \PC_next_MEM[1] , \PC_next_MEM[0]  }),
    .RegWrite(RegWrite_EX),
    .RegWrite_MEM(RegWrite_MEM),
    .ResultSrc({ \ResultSrc_EX[1] , \ResultSrc_EX[0]  }),
    .ResultSrc_MEM({ \ResultSrc_MEM[1] , \ResultSrc_MEM[0]  }),
    .clk(clk),
    .rd_EXMEM({ \rd_ID_EX_EX[4] , \rd_ID_EX_EX[3] , \rd_ID_EX_EX[2] , \rd_ID_EX_EX[1] , \rd_ID_EX_EX[0]  }),
    .rd_EXMEM_MEM({ \rd_EXMEM_MEM[4] , \rd_EXMEM_MEM[3] , \rd_EXMEM_MEM[2] , \rd_EXMEM_MEM[1] , \rd_EXMEM_MEM[0]  }),
    .rst(rst),
    .stall_EX(stall_EX),
    .stall_MEM(stall_MEM)
  );
  multiplex_3x1 MUX_PC_Data (
    .A({ \data1_ID_ForwA[31] , \data1_ID_ForwA[30] , \data1_ID_ForwA[29] , \data1_ID_ForwA[28] , \data1_ID_ForwA[27] , \data1_ID_ForwA[26] , \data1_ID_ForwA[25] , \data1_ID_ForwA[24] , \data1_ID_ForwA[23] , \data1_ID_ForwA[22] , \data1_ID_ForwA[21] , \data1_ID_ForwA[20] , \data1_ID_ForwA[19] , \data1_ID_ForwA[18] , \data1_ID_ForwA[17] , \data1_ID_ForwA[16] , \data1_ID_ForwA[15] , \data1_ID_ForwA[14] , \data1_ID_ForwA[13] , \data1_ID_ForwA[12] , \data1_ID_ForwA[11] , \data1_ID_ForwA[10] , \data1_ID_ForwA[9] , \data1_ID_ForwA[8] , \data1_ID_ForwA[7] , \data1_ID_ForwA[6] , \data1_ID_ForwA[5] , \data1_ID_ForwA[4] , \data1_ID_ForwA[3] , \data1_ID_ForwA[2] , \data1_ID_ForwA[1] , \data1_ID_ForwA[0]  }),
    .B({ \PC_ID[31] , \PC_ID[30] , \PC_ID[29] , \PC_ID[28] , \PC_ID[27] , \PC_ID[26] , \PC_ID[25] , \PC_ID[24] , \PC_ID[23] , \PC_ID[22] , \PC_ID[21] , \PC_ID[20] , \PC_ID[19] , \PC_ID[18] , \PC_ID[17] , \PC_ID[16] , \PC_ID[15] , \PC_ID[14] , \PC_ID[13] , \PC_ID[12] , \PC_ID[11] , \PC_ID[10] , \PC_ID[9] , \PC_ID[8] , \PC_ID[7] , \PC_ID[6] , \PC_ID[5] , \PC_ID[4] , \PC_ID[3] , \PC_ID[2] , \PC_ID[1] , \PC_ID[0]  }),
    .C(32'd0),
    .D(32'd0),
    .Result({ \rdA[31] , \rdA[30] , \rdA[29] , \rdA[28] , \rdA[27] , \rdA[26] , \rdA[25] , \rdA[24] , \rdA[23] , \rdA[22] , \rdA[21] , \rdA[20] , \rdA[19] , \rdA[18] , \rdA[17] , \rdA[16] , \rdA[15] , \rdA[14] , \rdA[13] , \rdA[12] , \rdA[11] , \rdA[10] , \rdA[9] , \rdA[8] , \rdA[7] , \rdA[6] , \rdA[5] , \rdA[4] , \rdA[3] , \rdA[2] , \rdA[1] , \rdA[0]  }),
    .sel({ \isPC_select_ID[1] , \isPC_select_ID[0]  })
  );
  Multiplexer MultiPC (
    .A({ \PCPlus4[31] , \PCPlus4[30] , \PCPlus4[29] , \PCPlus4[28] , \PCPlus4[27] , \PCPlus4[26] , \PCPlus4[25] , \PCPlus4[24] , \PCPlus4[23] , \PCPlus4[22] , \PCPlus4[21] , \PCPlus4[20] , \PCPlus4[19] , \PCPlus4[18] , \PCPlus4[17] , \PCPlus4[16] , \PCPlus4[15] , \PCPlus4[14] , \PCPlus4[13] , \PCPlus4[12] , \PCPlus4[11] , \PCPlus4[10] , \PCPlus4[9] , \PCPlus4[8] , \PCPlus4[7] , \PCPlus4[6] , \PCPlus4[5] , \PCPlus4[4] , \PCPlus4[3] , \PCPlus4[2] , \PCPlus4[1] , \PCPlus4[0]  }),
    .B({ \PC_ALU_Sum[31] , \PC_ALU_Sum[30] , \PC_ALU_Sum[29] , \PC_ALU_Sum[28] , \PC_ALU_Sum[27] , \PC_ALU_Sum[26] , \PC_ALU_Sum[25] , \PC_ALU_Sum[24] , \PC_ALU_Sum[23] , \PC_ALU_Sum[22] , \PC_ALU_Sum[21] , \PC_ALU_Sum[20] , \PC_ALU_Sum[19] , \PC_ALU_Sum[18] , \PC_ALU_Sum[17] , \PC_ALU_Sum[16] , \PC_ALU_Sum[15] , \PC_ALU_Sum[14] , \PC_ALU_Sum[13] , \PC_ALU_Sum[12] , \PC_ALU_Sum[11] , \PC_ALU_Sum[10] , \PC_ALU_Sum[9] , \PC_ALU_Sum[8] , \PC_ALU_Sum[7] , \PC_ALU_Sum[6] , \PC_ALU_Sum[5] , \PC_ALU_Sum[4] , \PC_ALU_Sum[3] , \PC_ALU_Sum[2] , \PC_ALU_Sum[1] , \PC_ALU_Sum[0]  }),
    .Out({ \PC_next[31] , \PC_next[30] , \PC_next[29] , \PC_next[28] , \PC_next[27] , \PC_next[26] , \PC_next[25] , \PC_next[24] , \PC_next[23] , \PC_next[22] , \PC_next[21] , \PC_next[20] , \PC_next[19] , \PC_next[18] , \PC_next[17] , \PC_next[16] , \PC_next[15] , \PC_next[14] , \PC_next[13] , \PC_next[12] , \PC_next[11] , \PC_next[10] , \PC_next[9] , \PC_next[8] , \PC_next[7] , \PC_next[6] , \PC_next[5] , \PC_next[4] , \PC_next[3] , \PC_next[2] , \PC_next[1] , \PC_next[0]  }),
    .sel(PCSrc)
  );
  Multiplexer Multiplex_ALU (
    .A({ \rdB_ForwB[31] , \rdB_ForwB[30] , \rdB_ForwB[29] , \rdB_ForwB[28] , \rdB_ForwB[27] , \rdB_ForwB[26] , \rdB_ForwB[25] , \rdB_ForwB[24] , \rdB_ForwB[23] , \rdB_ForwB[22] , \rdB_ForwB[21] , \rdB_ForwB[20] , \rdB_ForwB[19] , \rdB_ForwB[18] , \rdB_ForwB[17] , \rdB_ForwB[16] , \rdB_ForwB[15] , \rdB_ForwB[14] , \rdB_ForwB[13] , \rdB_ForwB[12] , \rdB_ForwB[11] , \rdB_ForwB[10] , \rdB_ForwB[9] , \rdB_ForwB[8] , \rdB_ForwB[7] , \rdB_ForwB[6] , \rdB_ForwB[5] , \rdB_ForwB[4] , \rdB_ForwB[3] , \rdB_ForwB[2] , \rdB_ForwB[1] , \rdB_ForwB[0]  }),
    .B({ \ImmExt_ID[31] , \ImmExt_ID[30] , \ImmExt_ID[29] , \ImmExt_ID[28] , \ImmExt_ID[27] , \ImmExt_ID[26] , \ImmExt_ID[25] , \ImmExt_ID[24] , \ImmExt_ID[23] , \ImmExt_ID[22] , \ImmExt_ID[21] , \ImmExt_ID[20] , \ImmExt_ID[19] , \ImmExt_ID[18] , \ImmExt_ID[17] , \ImmExt_ID[16] , \ImmExt_ID[15] , \ImmExt_ID[14] , \ImmExt_ID[13] , \ImmExt_ID[12] , \ImmExt_ID[11] , \ImmExt_ID[10] , \ImmExt_ID[9] , \ImmExt_ID[8] , \ImmExt_ID[7] , \ImmExt_ID[6] , \ImmExt_ID[5] , \ImmExt_ID[4] , \ImmExt_ID[3] , \ImmExt_ID[2] , \ImmExt_ID[1] , \ImmExt_ID[0]  }),
    .Out({ \rdB[31] , \rdB[30] , \rdB[29] , \rdB[28] , \rdB[27] , \rdB[26] , \rdB[25] , \rdB[24] , \rdB[23] , \rdB[22] , \rdB[21] , \rdB[20] , \rdB[19] , \rdB[18] , \rdB[17] , \rdB[16] , \rdB[15] , \rdB[14] , \rdB[13] , \rdB[12] , \rdB[11] , \rdB[10] , \rdB[9] , \rdB[8] , \rdB[7] , \rdB[6] , \rdB[5] , \rdB[4] , \rdB[3] , \rdB[2] , \rdB[1] , \rdB[0]  }),
    .sel(ALUSrc_ID)
  );
  Multiplexer Multiplex_jump_branch (
    .A({ \PC_Branch[31] , \PC_Branch[30] , \PC_Branch[29] , \PC_Branch[28] , \PC_Branch[27] , \PC_Branch[26] , \PC_Branch[25] , \PC_Branch[24] , \PC_Branch[23] , \PC_Branch[22] , \PC_Branch[21] , \PC_Branch[20] , \PC_Branch[19] , \PC_Branch[18] , \PC_Branch[17] , \PC_Branch[16] , \PC_Branch[15] , \PC_Branch[14] , \PC_Branch[13] , \PC_Branch[12] , \PC_Branch[11] , \PC_Branch[10] , \PC_Branch[9] , \PC_Branch[8] , \PC_Branch[7] , \PC_Branch[6] , \PC_Branch[5] , \PC_Branch[4] , \PC_Branch[3] , \PC_Branch[2] , \PC_Branch[1] , \PC_Branch[0]  }),
    .B({ \ALUresult[31] , \ALUresult[30] , \ALUresult[29] , \ALUresult[28] , \ALUresult[27] , \ALUresult[26] , \ALUresult[25] , \ALUresult[24] , \ALUresult[23] , \ALUresult[22] , \ALUresult[21] , \ALUresult[20] , \ALUresult[19] , \ALUresult[18] , \ALUresult[17] , \ALUresult[16] , \ALUresult[15] , \ALUresult[14] , \ALUresult[13] , \ALUresult[12] , \ALUresult[11] , \ALUresult[10] , \ALUresult[9] , \ALUresult[8] , \ALUresult[7] , \ALUresult[6] , \ALUresult[5] , \ALUresult[4] , \ALUresult[3] , \ALUresult[2] , \ALUresult[1] , \ALUresult[0]  }),
    .Out({ \PC_ALU_Sum[31] , \PC_ALU_Sum[30] , \PC_ALU_Sum[29] , \PC_ALU_Sum[28] , \PC_ALU_Sum[27] , \PC_ALU_Sum[26] , \PC_ALU_Sum[25] , \PC_ALU_Sum[24] , \PC_ALU_Sum[23] , \PC_ALU_Sum[22] , \PC_ALU_Sum[21] , \PC_ALU_Sum[20] , \PC_ALU_Sum[19] , \PC_ALU_Sum[18] , \PC_ALU_Sum[17] , \PC_ALU_Sum[16] , \PC_ALU_Sum[15] , \PC_ALU_Sum[14] , \PC_ALU_Sum[13] , \PC_ALU_Sum[12] , \PC_ALU_Sum[11] , \PC_ALU_Sum[10] , \PC_ALU_Sum[9] , \PC_ALU_Sum[8] , \PC_ALU_Sum[7] , \PC_ALU_Sum[6] , \PC_ALU_Sum[5] , \PC_ALU_Sum[4] , \PC_ALU_Sum[3] , \PC_ALU_Sum[2] , \PC_ALU_Sum[1] , \PC_ALU_Sum[0]  }),
    .sel(JumpReg_ID)
  );
  PC PC0 (
    .PC({ \PC[31] , \PC[30] , \PC[29] , \PC[28] , \PC[27] , \PC[26] , \PC[25] , \PC[24] , \PC[23] , \PC[22] , \PC[21] , \PC[20] , \PC[19] , \PC[18] , \PC[17] , \PC[16] , \PC[15] , \PC[14] , \PC[13] , \PC[12] , \PC[11] , \PC[10] , \PC[9] , \PC[8] , \PC[7] , \PC[6] , \PC[5] , \PC[4] , \PC[3] , \PC[2] , \PC[1] , \PC[0]  }),
    .PCWrite(_221_),
    .PC_next({ \PC_next[31] , \PC_next[30] , \PC_next[29] , \PC_next[28] , \PC_next[27] , \PC_next[26] , \PC_next[25] , \PC_next[24] , \PC_next[23] , \PC_next[22] , \PC_next[21] , \PC_next[20] , \PC_next[19] , \PC_next[18] , \PC_next[17] , \PC_next[16] , \PC_next[15] , \PC_next[14] , \PC_next[13] , \PC_next[12] , \PC_next[11] , \PC_next[10] , \PC_next[9] , \PC_next[8] , \PC_next[7] , \PC_next[6] , \PC_next[5] , \PC_next[4] , \PC_next[3] , \PC_next[2] , \PC_next[1] , \PC_next[0]  }),
    .clk(clk),
    .rst(rst)
  );
  PC_ALU_Adder PC_ALU_Adder0 (
    .A({ \PC_ID[31] , \PC_ID[30] , \PC_ID[29] , \PC_ID[28] , \PC_ID[27] , \PC_ID[26] , \PC_ID[25] , \PC_ID[24] , \PC_ID[23] , \PC_ID[22] , \PC_ID[21] , \PC_ID[20] , \PC_ID[19] , \PC_ID[18] , \PC_ID[17] , \PC_ID[16] , \PC_ID[15] , \PC_ID[14] , \PC_ID[13] , \PC_ID[12] , \PC_ID[11] , \PC_ID[10] , \PC_ID[9] , \PC_ID[8] , \PC_ID[7] , \PC_ID[6] , \PC_ID[5] , \PC_ID[4] , \PC_ID[3] , \PC_ID[2] , \PC_ID[1] , \PC_ID[0]  }),
    .B({ \ImmExt_ID[31] , \ImmExt_ID[30] , \ImmExt_ID[29] , \ImmExt_ID[28] , \ImmExt_ID[27] , \ImmExt_ID[26] , \ImmExt_ID[25] , \ImmExt_ID[24] , \ImmExt_ID[23] , \ImmExt_ID[22] , \ImmExt_ID[21] , \ImmExt_ID[20] , \ImmExt_ID[19] , \ImmExt_ID[18] , \ImmExt_ID[17] , \ImmExt_ID[16] , \ImmExt_ID[15] , \ImmExt_ID[14] , \ImmExt_ID[13] , \ImmExt_ID[12] , \ImmExt_ID[11] , \ImmExt_ID[10] , \ImmExt_ID[9] , \ImmExt_ID[8] , \ImmExt_ID[7] , \ImmExt_ID[6] , \ImmExt_ID[5] , \ImmExt_ID[4] , \ImmExt_ID[3] , \ImmExt_ID[2] , \ImmExt_ID[1] , \ImmExt_ID[0]  }),
    .Sum({ \PC_Branch[31] , \PC_Branch[30] , \PC_Branch[29] , \PC_Branch[28] , \PC_Branch[27] , \PC_Branch[26] , \PC_Branch[25] , \PC_Branch[24] , \PC_Branch[23] , \PC_Branch[22] , \PC_Branch[21] , \PC_Branch[20] , \PC_Branch[19] , \PC_Branch[18] , \PC_Branch[17] , \PC_Branch[16] , \PC_Branch[15] , \PC_Branch[14] , \PC_Branch[13] , \PC_Branch[12] , \PC_Branch[11] , \PC_Branch[10] , \PC_Branch[9] , \PC_Branch[8] , \PC_Branch[7] , \PC_Branch[6] , \PC_Branch[5] , \PC_Branch[4] , \PC_Branch[3] , \PC_Branch[2] , \PC_Branch[1] , \PC_Branch[0]  })
  );
  PCPlus4 PCplus4 (
    .PC({ \PC[31] , \PC[30] , \PC[29] , \PC[28] , \PC[27] , \PC[26] , \PC[25] , \PC[24] , \PC[23] , \PC[22] , \PC[21] , \PC[20] , \PC[19] , \PC[18] , \PC[17] , \PC[16] , \PC[15] , \PC[14] , \PC[13] , \PC[12] , \PC[11] , \PC[10] , \PC[9] , \PC[8] , \PC[7] , \PC[6] , \PC[5] , \PC[4] , \PC[3] , \PC[2] , \PC[1] , \PC[0]  }),
    .PCPlus4({ \PCPlus4[31] , \PCPlus4[30] , \PCPlus4[29] , \PCPlus4[28] , \PCPlus4[27] , \PCPlus4[26] , \PCPlus4[25] , \PCPlus4[24] , \PCPlus4[23] , \PCPlus4[22] , \PCPlus4[21] , \PCPlus4[20] , \PCPlus4[19] , \PCPlus4[18] , \PCPlus4[17] , \PCPlus4[16] , \PCPlus4[15] , \PCPlus4[14] , \PCPlus4[13] , \PCPlus4[12] , \PCPlus4[11] , \PCPlus4[10] , \PCPlus4[9] , \PCPlus4[8] , \PCPlus4[7] , \PCPlus4[6] , \PCPlus4[5] , \PCPlus4[4] , \PCPlus4[3] , \PCPlus4[2] , \PCPlus4[1] , \PCPlus4[0]  }),
    .rst(rst)
  );
  Register Register (
    .RegWrite(_219_),
    .RegWriteData({ \Result[31] , \Result[30] , \Result[29] , \Result[28] , \Result[27] , \Result[26] , \Result[25] , \Result[24] , \Result[23] , \Result[22] , \Result[21] , \Result[20] , \Result[19] , \Result[18] , \Result[17] , \Result[16] , \Result[15] , \Result[14] , \Result[13] , \Result[12] , \Result[11] , \Result[10] , \Result[9] , \Result[8] , \Result[7] , \Result[6] , \Result[5] , \Result[4] , \Result[3] , \Result[2] , \Result[1] , \Result[0]  }),
    .clk(clk),
    .data1({ \rf_data1[31] , \rf_data1[30] , \rf_data1[29] , \rf_data1[28] , \rf_data1[27] , \rf_data1[26] , \rf_data1[25] , \rf_data1[24] , \rf_data1[23] , \rf_data1[22] , \rf_data1[21] , \rf_data1[20] , \rf_data1[19] , \rf_data1[18] , \rf_data1[17] , \rf_data1[16] , \rf_data1[15] , \rf_data1[14] , \rf_data1[13] , \rf_data1[12] , \rf_data1[11] , \rf_data1[10] , \rf_data1[9] , \rf_data1[8] , \rf_data1[7] , \rf_data1[6] , \rf_data1[5] , \rf_data1[4] , \rf_data1[3] , \rf_data1[2] , \rf_data1[1] , \rf_data1[0]  }),
    .data2({ \rf_data2[31] , \rf_data2[30] , \rf_data2[29] , \rf_data2[28] , \rf_data2[27] , \rf_data2[26] , \rf_data2[25] , \rf_data2[24] , \rf_data2[23] , \rf_data2[22] , \rf_data2[21] , \rf_data2[20] , \rf_data2[19] , \rf_data2[18] , \rf_data2[17] , \rf_data2[16] , \rf_data2[15] , \rf_data2[14] , \rf_data2[13] , \rf_data2[12] , \rf_data2[11] , \rf_data2[10] , \rf_data2[9] , \rf_data2[8] , \rf_data2[7] , \rf_data2[6] , \rf_data2[5] , \rf_data2[4] , \rf_data2[3] , \rf_data2[2] , \rf_data2[1] , \rf_data2[0]  }),
    .rs1({ \instruction_IF[19] , \instruction_IF[18] , \instruction_IF[17] , \instruction_IF[16] , \instruction_IF[15]  }),
    .rs2({ \instruction_IF[24] , \instruction_IF[23] , \instruction_IF[22] , \instruction_IF[21] , \instruction_IF[20]  }),
    .rst(rst),
    .w_add({ \rd_EXMEM_MEM[4] , \rd_EXMEM_MEM[3] , \rd_EXMEM_MEM[2] , \rd_EXMEM_MEM[1] , \rd_EXMEM_MEM[0]  })
  );
  Reset_Sync Reset_Sync (
    .async_rst(async_rst),
    .clk(clk),
    .sync_rst(rst)
  );
  UART_addr_sel UART_addr_sel (
    .ALUresult({ \ALUresult_EX[31] , \ALUresult_EX[30] , \ALUresult_EX[29] , \ALUresult_EX[28] , \ALUresult_EX[27] , \ALUresult_EX[26] , \ALUresult_EX[25] , \ALUresult_EX[24] , \ALUresult_EX[23] , \ALUresult_EX[22] , \ALUresult_EX[21] , \ALUresult_EX[20] , \ALUresult_EX[19] , \ALUresult_EX[18] , \ALUresult_EX[17] , \ALUresult_EX[16] , \ALUresult_EX[15] , \ALUresult_EX[14] , \ALUresult_EX[13] , \ALUresult_EX[12] , \ALUresult_EX[11] , \ALUresult_EX[10] , \ALUresult_EX[9] , \ALUresult_EX[8] , \ALUresult_EX[7] , \ALUresult_EX[6] , \ALUresult_EX[5] , \ALUresult_EX[4] , \ALUresult_EX[3] , \ALUresult_EX[2] , \ALUresult_EX[1] , \ALUresult_EX[0]  }),
    .IO_OUT({ \IO_OUT[15] , \IO_OUT[14] , \IO_OUT[13] , \IO_OUT[12] , \IO_OUT[11] , \IO_OUT[10] , \IO_OUT[9] , \IO_OUT[8] , \IO_OUT[7] , \IO_OUT[6] , \IO_OUT[5] , \IO_OUT[4] , \IO_OUT[3] , \IO_OUT[2] , \IO_OUT[1] , \IO_OUT[0]  }),
    .IO_OUT_temp({ \data2_EX[15] , \data2_EX[14] , \data2_EX[13] , \data2_EX[12] , \data2_EX[11] , \data2_EX[10] , \data2_EX[9] , \data2_EX[8] , \data2_EX[7] , \data2_EX[6] , \data2_EX[5] , \data2_EX[4] , \data2_EX[3] , \data2_EX[2] , \data2_EX[1] , \data2_EX[0]  }),
    .MemWrite(\Mem_Con_EX[1] ),
    .UART_Mem_wt({ \UART_Mem_wt[1] , \UART_Mem_wt[0]  }),
    .rst(rst)
  );
  Multiplexer compressed_multiplex (
    .A({ \initial_instr[31] , \initial_instr[30] , \initial_instr[29] , \initial_instr[28] , \initial_instr[27] , \initial_instr[26] , \initial_instr[25] , \initial_instr[24] , \initial_instr[23] , \initial_instr[22] , \initial_instr[21] , \initial_instr[20] , \initial_instr[19] , \initial_instr[18] , \initial_instr[17] , \initial_instr[16] , \initial_instr[15] , \initial_instr[14] , \initial_instr[13] , \initial_instr[12] , \initial_instr[11] , \initial_instr[10] , \initial_instr[9] , \initial_instr[8] , \initial_instr[7] , \initial_instr[6] , \initial_instr[5] , \initial_instr[4] , \initial_instr[3] , \initial_instr[2] , \initial_instr[1] , \initial_instr[0]  }),
    .B({ \compress_instr[31] , \compress_instr[30] , \compress_instr[29] , \compress_instr[28] , \compress_instr[27] , \compress_instr[26] , \compress_instr[25] , \compress_instr[24] , \compress_instr[23] , \compress_instr[22] , \compress_instr[21] , \compress_instr[20] , \compress_instr[19] , \compress_instr[18] , \compress_instr[17] , \compress_instr[16] , \compress_instr[15] , \compress_instr[14] , \compress_instr[13] , \compress_instr[12] , \compress_instr[11] , \compress_instr[10] , \compress_instr[9] , \compress_instr[8] , \compress_instr[7] , \compress_instr[6] , \compress_instr[5] , \compress_instr[4] , \compress_instr[3] , \compress_instr[2] , \compress_instr[1] , \compress_instr[0]  }),
    .Out({ \instruction[31] , \instruction[30] , \instruction[29] , \instruction[28] , \instruction[27] , \instruction[26] , \instruction[25] , \instruction[24] , \instruction[23] , \instruction[22] , \instruction[21] , \instruction[20] , \instruction[19] , \instruction[18] , \instruction[17] , \instruction[16] , \instruction[15] , \instruction[14] , \instruction[13] , \instruction[12] , \instruction[11] , \instruction[10] , \instruction[9] , \instruction[8] , \instruction[7] , \instruction[6] , \instruction[5] , \instruction[4] , \instruction[3] , \instruction[2] , \instruction[1] , \instruction[0]  }),
    .sel(is_compressed)
  );
  FIFO_UART_top fifo_uart (
    .FIFO_Rx_Dout({ \FIFO_Rx_Dout[7] , \FIFO_Rx_Dout[6] , \FIFO_Rx_Dout[5] , \FIFO_Rx_Dout[4] , \FIFO_Rx_Dout[3] , \FIFO_Rx_Dout[2] , \FIFO_Rx_Dout[1] , \FIFO_Rx_Dout[0]  }),
    .Rx_Serial(Rx_Serial),
    .Rx_read_en(Rx_read_en),
    .Tx_Din({ \data2_EX[7] , \data2_EX[6] , \data2_EX[5] , \data2_EX[4] , \data2_EX[3] , \data2_EX[2] , \data2_EX[1] , \data2_EX[0]  }),
    .Tx_Serial(Tx_Serial),
    .clk(clk),
    .empty_Rx(empty_Rx),
    .full_Rx(full_Rx),
    .rst(rst),
    .write_en(_251_)
  );
  mult_div_stall mult_div_stall (
    .div_active(div_active),
    .mul_active(mul_active),
    .rst(rst),
    .stall(stall)
  );
  multiplex_3x1 multipplex_result0 (
    .A({ \ALUresult_MEM[31] , \ALUresult_MEM[30] , \ALUresult_MEM[29] , \ALUresult_MEM[28] , \ALUresult_MEM[27] , \ALUresult_MEM[26] , \ALUresult_MEM[25] , \ALUresult_MEM[24] , \ALUresult_MEM[23] , \ALUresult_MEM[22] , \ALUresult_MEM[21] , \ALUresult_MEM[20] , \ALUresult_MEM[19] , \ALUresult_MEM[18] , \ALUresult_MEM[17] , \ALUresult_MEM[16] , \ALUresult_MEM[15] , \ALUresult_MEM[14] , \ALUresult_MEM[13] , \ALUresult_MEM[12] , \ALUresult_MEM[11] , \ALUresult_MEM[10] , \ALUresult_MEM[9] , \ALUresult_MEM[8] , \ALUresult_MEM[7] , \ALUresult_MEM[6] , \ALUresult_MEM[5] , \ALUresult_MEM[4] , \ALUresult_MEM[3] , \ALUresult_MEM[2] , \ALUresult_MEM[1] , \ALUresult_MEM[0]  }),
    .B({ \MemReadData_MEM[31] , \MemReadData_MEM[30] , \MemReadData_MEM[29] , \MemReadData_MEM[28] , \MemReadData_MEM[27] , \MemReadData_MEM[26] , \MemReadData_MEM[25] , \MemReadData_MEM[24] , \MemReadData_MEM[23] , \MemReadData_MEM[22] , \MemReadData_MEM[21] , \MemReadData_MEM[20] , \MemReadData_MEM[19] , \MemReadData_MEM[18] , \MemReadData_MEM[17] , \MemReadData_MEM[16] , \MemReadData_MEM[15] , \MemReadData_MEM[14] , \MemReadData_MEM[13] , \MemReadData_MEM[12] , \MemReadData_MEM[11] , \MemReadData_MEM[10] , \MemReadData_MEM[9] , \MemReadData_MEM[8] , \MemReadData_MEM[7] , \MemReadData_MEM[6] , \MemReadData_MEM[5] , \MemReadData_MEM[4] , \MemReadData_MEM[3] , \MemReadData_MEM[2] , \MemReadData_MEM[1] , \MemReadData_MEM[0]  }),
    .C({ \PC_next_MEM[31] , \PC_next_MEM[30] , \PC_next_MEM[29] , \PC_next_MEM[28] , \PC_next_MEM[27] , \PC_next_MEM[26] , \PC_next_MEM[25] , \PC_next_MEM[24] , \PC_next_MEM[23] , \PC_next_MEM[22] , \PC_next_MEM[21] , \PC_next_MEM[20] , \PC_next_MEM[19] , \PC_next_MEM[18] , \PC_next_MEM[17] , \PC_next_MEM[16] , \PC_next_MEM[15] , \PC_next_MEM[14] , \PC_next_MEM[13] , \PC_next_MEM[12] , \PC_next_MEM[11] , \PC_next_MEM[10] , \PC_next_MEM[9] , \PC_next_MEM[8] , \PC_next_MEM[7] , \PC_next_MEM[6] , \PC_next_MEM[5] , \PC_next_MEM[4] , \PC_next_MEM[3] , \PC_next_MEM[2] , \PC_next_MEM[1] , \PC_next_MEM[0]  }),
    .D(32'd0),
    .Result({ \Result[31] , \Result[30] , \Result[29] , \Result[28] , \Result[27] , \Result[26] , \Result[25] , \Result[24] , \Result[23] , \Result[22] , \Result[21] , \Result[20] , \Result[19] , \Result[18] , \Result[17] , \Result[16] , \Result[15] , \Result[14] , \Result[13] , \Result[12] , \Result[11] , \Result[10] , \Result[9] , \Result[8] , \Result[7] , \Result[6] , \Result[5] , \Result[4] , \Result[3] , \Result[2] , \Result[1] , \Result[0]  }),
    .sel({ \ResultSrc_MEM[1] , \ResultSrc_MEM[0]  })
  );
  assign _041_ = \UART_Mem_wt[0] ;
  assign _042_ = \UART_Mem_wt[1] ;
  assign _007_ = PCWriteEN;
  assign _221_ = _046_;
  assign _002_ = IF_ID_WriteEN;
  assign _222_ = _047_;
  assign _008_ = RegWrite_MEM;
  assign _219_ = _044_;
  assign _220_ = _045_;
  assign _004_ = Jump_ID;
  assign _003_ = JumpReg_ID;
  assign _043_ = Zero;
  assign _000_ = B_Zero_ID;
  assign _001_ = Branch_ID;
  assign _147_ = \rd_EXMEM_MEM[0] ;
  assign _113_ = \instruction_IF[15] ;
  assign _148_ = \rd_EXMEM_MEM[1] ;
  assign _114_ = \instruction_IF[16] ;
  assign _149_ = \rd_EXMEM_MEM[2] ;
  assign _115_ = \instruction_IF[17] ;
  assign _150_ = \rd_EXMEM_MEM[3] ;
  assign _116_ = \instruction_IF[18] ;
  assign _151_ = \rd_EXMEM_MEM[4] ;
  assign _117_ = \instruction_IF[19] ;
  assign _118_ = \instruction_IF[20] ;
  assign _119_ = \instruction_IF[21] ;
  assign _120_ = \instruction_IF[22] ;
  assign _121_ = \instruction_IF[23] ;
  assign _122_ = \instruction_IF[24] ;
  assign _251_ = _112_;
  assign _005_ = \Mem_Con_EX[1] ;
  assign _252_ = _123_;
  assign _216_ = rst;
  assign PCSrc = _006_;
  assign _152_ = \rf_data1[0] ;
  assign _009_ = \Result[0] ;
  assign \data1[0]  = _048_;
  assign _163_ = \rf_data1[1] ;
  assign _020_ = \Result[1] ;
  assign \data1[1]  = _059_;
  assign _174_ = \rf_data1[2] ;
  assign _031_ = \Result[2] ;
  assign \data1[2]  = _070_;
  assign _177_ = \rf_data1[3] ;
  assign _034_ = \Result[3] ;
  assign \data1[3]  = _073_;
  assign _178_ = \rf_data1[4] ;
  assign _035_ = \Result[4] ;
  assign \data1[4]  = _074_;
  assign _179_ = \rf_data1[5] ;
  assign _036_ = \Result[5] ;
  assign \data1[5]  = _075_;
  assign _180_ = \rf_data1[6] ;
  assign _037_ = \Result[6] ;
  assign \data1[6]  = _076_;
  assign _181_ = \rf_data1[7] ;
  assign _038_ = \Result[7] ;
  assign \data1[7]  = _077_;
  assign _182_ = \rf_data1[8] ;
  assign _039_ = \Result[8] ;
  assign \data1[8]  = _078_;
  assign _183_ = \rf_data1[9] ;
  assign _040_ = \Result[9] ;
  assign \data1[9]  = _079_;
  assign _153_ = \rf_data1[10] ;
  assign _010_ = \Result[10] ;
  assign \data1[10]  = _049_;
  assign _154_ = \rf_data1[11] ;
  assign _011_ = \Result[11] ;
  assign \data1[11]  = _050_;
  assign _155_ = \rf_data1[12] ;
  assign _012_ = \Result[12] ;
  assign \data1[12]  = _051_;
  assign _156_ = \rf_data1[13] ;
  assign _013_ = \Result[13] ;
  assign \data1[13]  = _052_;
  assign _157_ = \rf_data1[14] ;
  assign _014_ = \Result[14] ;
  assign \data1[14]  = _053_;
  assign _158_ = \rf_data1[15] ;
  assign _015_ = \Result[15] ;
  assign \data1[15]  = _054_;
  assign _159_ = \rf_data1[16] ;
  assign _016_ = \Result[16] ;
  assign \data1[16]  = _055_;
  assign _160_ = \rf_data1[17] ;
  assign _017_ = \Result[17] ;
  assign \data1[17]  = _056_;
  assign _161_ = \rf_data1[18] ;
  assign _018_ = \Result[18] ;
  assign \data1[18]  = _057_;
  assign _162_ = \rf_data1[19] ;
  assign _019_ = \Result[19] ;
  assign \data1[19]  = _058_;
  assign _164_ = \rf_data1[20] ;
  assign _021_ = \Result[20] ;
  assign \data1[20]  = _060_;
  assign _165_ = \rf_data1[21] ;
  assign _022_ = \Result[21] ;
  assign \data1[21]  = _061_;
  assign _166_ = \rf_data1[22] ;
  assign _023_ = \Result[22] ;
  assign \data1[22]  = _062_;
  assign _167_ = \rf_data1[23] ;
  assign _024_ = \Result[23] ;
  assign \data1[23]  = _063_;
  assign _168_ = \rf_data1[24] ;
  assign _025_ = \Result[24] ;
  assign \data1[24]  = _064_;
  assign _169_ = \rf_data1[25] ;
  assign _026_ = \Result[25] ;
  assign \data1[25]  = _065_;
  assign _170_ = \rf_data1[26] ;
  assign _027_ = \Result[26] ;
  assign \data1[26]  = _066_;
  assign _171_ = \rf_data1[27] ;
  assign _028_ = \Result[27] ;
  assign \data1[27]  = _067_;
  assign _172_ = \rf_data1[28] ;
  assign _029_ = \Result[28] ;
  assign \data1[28]  = _068_;
  assign _173_ = \rf_data1[29] ;
  assign _030_ = \Result[29] ;
  assign \data1[29]  = _069_;
  assign _175_ = \rf_data1[30] ;
  assign _032_ = \Result[30] ;
  assign \data1[30]  = _071_;
  assign _176_ = \rf_data1[31] ;
  assign _033_ = \Result[31] ;
  assign \data1[31]  = _072_;
  assign _184_ = \rf_data2[0] ;
  assign \data2[0]  = _080_;
  assign _195_ = \rf_data2[1] ;
  assign \data2[1]  = _091_;
  assign _206_ = \rf_data2[2] ;
  assign \data2[2]  = _102_;
  assign _209_ = \rf_data2[3] ;
  assign \data2[3]  = _105_;
  assign _210_ = \rf_data2[4] ;
  assign \data2[4]  = _106_;
  assign _211_ = \rf_data2[5] ;
  assign \data2[5]  = _107_;
  assign _212_ = \rf_data2[6] ;
  assign \data2[6]  = _108_;
  assign _213_ = \rf_data2[7] ;
  assign \data2[7]  = _109_;
  assign _214_ = \rf_data2[8] ;
  assign \data2[8]  = _110_;
  assign _215_ = \rf_data2[9] ;
  assign \data2[9]  = _111_;
  assign _185_ = \rf_data2[10] ;
  assign \data2[10]  = _081_;
  assign _186_ = \rf_data2[11] ;
  assign \data2[11]  = _082_;
  assign _187_ = \rf_data2[12] ;
  assign \data2[12]  = _083_;
  assign _188_ = \rf_data2[13] ;
  assign \data2[13]  = _084_;
  assign _189_ = \rf_data2[14] ;
  assign \data2[14]  = _085_;
  assign _190_ = \rf_data2[15] ;
  assign \data2[15]  = _086_;
  assign _191_ = \rf_data2[16] ;
  assign \data2[16]  = _087_;
  assign _192_ = \rf_data2[17] ;
  assign \data2[17]  = _088_;
  assign _193_ = \rf_data2[18] ;
  assign \data2[18]  = _089_;
  assign _194_ = \rf_data2[19] ;
  assign \data2[19]  = _090_;
  assign _196_ = \rf_data2[20] ;
  assign \data2[20]  = _092_;
  assign _197_ = \rf_data2[21] ;
  assign \data2[21]  = _093_;
  assign _198_ = \rf_data2[22] ;
  assign \data2[22]  = _094_;
  assign _199_ = \rf_data2[23] ;
  assign \data2[23]  = _095_;
  assign _200_ = \rf_data2[24] ;
  assign \data2[24]  = _096_;
  assign _201_ = \rf_data2[25] ;
  assign \data2[25]  = _097_;
  assign _202_ = \rf_data2[26] ;
  assign \data2[26]  = _098_;
  assign _203_ = \rf_data2[27] ;
  assign \data2[27]  = _099_;
  assign _204_ = \rf_data2[28] ;
  assign \data2[28]  = _100_;
  assign _205_ = \rf_data2[29] ;
  assign \data2[29]  = _101_;
  assign _207_ = \rf_data2[30] ;
  assign \data2[30]  = _103_;
  assign _208_ = \rf_data2[31] ;
  assign \data2[31]  = _104_;
  assign _217_ = stall;
  assign _218_ = stall_MEM;
endmodule
